'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Check,ChevronLeft,ChevronRight,Focus,Search} from 'lucide-react';
import {examModules,examSources,examUrl,local} from './exam-data';
import {normalizeSearch,type Language} from './i18n';
import StudyVisuals from './study-visuals';
import ExamQuiz from './exam-quiz';
import BookReading from './book-reading';
import {criterionDepth,topicCases} from './exam-depth';
import StudyChecklist from './study-checklist';
const progressKey='canine-atlas-exam-reviewed-v1';
export default function ExamStudy({language,onExplore,onPractical,initialTopic='anatomy',initialCriterion}:{language:Language;onExplore:(id:string)=>void;onPractical?:()=>void;initialTopic?:string;initialCriterion?:string}){
 const e=(en:string,cs:string)=>language==='cs'?cs:en;
 const [active,setActive]=useState(initialTopic),[query,setQuery]=useState(''),[reviewed,setReviewed]=useState<string[]>([]),[storageReady,setStorageReady]=useState(false),[storageError,setStorageError]=useState(false);
 const [screen,setScreen]=useState('lessons');
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(progressKey)||'[]');if(Array.isArray(raw))setReviewed([...new Set(raw.filter((id:unknown):id is string=>typeof id==='string'&&examModules.some(m=>m.id===id)))]);}catch{setStorageError(true);}setStorageReady(true);},[]);
 useEffect(()=>{if(!initialCriterion)return;const frame=requestAnimationFrame(()=>document.getElementById(`criterion-${initialTopic}-${initialCriterion}`)?.scrollIntoView({block:'start'}));return()=>cancelAnimationFrame(frame);},[initialTopic,initialCriterion]);
 const matches=useMemo(()=>examModules.filter(m=>normalizeSearch([m.title.en,m.title.cs,...m.sections.flatMap(s=>[s.title.en,s.title.cs,s.text.en,s.text.cs,criterionDepth[m.id][s.criteria].en,criterionDepth[m.id][s.criteria].cs]),...Object.values(topicCases[m.id]).flatMap(v=>[v.en,v.cs])].join(' ')).includes(normalizeSearch(query))),[query]);
 const selected=matches.find(m=>m.id===active)||matches[0];
 const previousTopic=useRef(active);
 useEffect(()=>{if(previousTopic.current===active)return;previousTopic.current=active;const panel=document.getElementById('exam-lesson');if(!panel)return;panel.querySelector<HTMLElement>('[data-lesson-heading]')?.focus({preventScroll:true});if(window.matchMedia('(max-width:760px)').matches)panel.scrollIntoView({block:'start'});else panel.scrollTo({top:0});},[active]);
 const index=examModules.findIndex(m=>m.id===selected?.id);
 const select=(id:string)=>{setActive(id);setQuery('');setScreen('lessons');document.getElementById('exam-lesson')?.scrollTo({top:0});};
 const toggleReview=()=>{if(!selected)return;const next=reviewed.includes(selected.id)?reviewed.filter(id=>id!==selected.id):[...reviewed,selected.id];setReviewed(next);try{localStorage.setItem(progressKey,JSON.stringify(next));setStorageError(false);}catch{setStorageError(true);}};
 return <section className="exam-shell" aria-label={e('Exam preparation','Příprava ke zkoušce')}>
  <aside className="exam-nav">
   <span className="eyebrow mint">{e('YOUR STUDY ROUTE','VAŠE STUDIJNÍ CESTA')}</span>
   <h2>{e('Exam preparation','Příprava ke zkoušce')}</h2>
   <p className="muted">{e('Qualification 43-001-R · dogs & cats','Kvalifikace 43-001-R · psi a kočky')}</p>
   <button className="exam-test-entry" aria-pressed={screen==='quiz'} onClick={()=>{setScreen('quiz');document.getElementById('exam-lesson')?.scrollTo({top:0});}}><Check size={18}/><span>{e('Test my knowledge','Otestovat znalosti')}<small>{e('Quizzes · pictures · revision','Testy · obrázky · opakování')}</small></span><ChevronRight size={16}/></button>
   <div className="exam-progress"><span>{e(`${reviewed.length} of 13 topics reviewed`,`${reviewed.length} z 13 témat zopakováno`)}</span><progress max={13} value={reviewed.length} aria-label={e('Topics marked reviewed','Témata označená jako zopakovaná')}/><small>{e('Saved on this device. Self-review, not an exam score.','Uloženo v tomto zařízení. Vlastní opakování, nikoli výsledek zkoušky.')}</small>{storageError&&<small role="status">{e('Progress cannot be saved in this browser.','V tomto prohlížeči nelze uložit postup.')}</small>}</div>
   <label className="search-field"><Search size={16}/><input value={query} onChange={ev=>setQuery(ev.target.value)} placeholder={e('Search topics in CZ / ENG…','Hledat témata v CZ / ENG…')} aria-label={e('Search exam topics','Hledat témata zkoušky')}/></label>
   <nav aria-label={e('Exam topics','Témata zkoušky')}>{matches.map(m=><button key={m.id} onClick={()=>{setActive(m.id);setScreen('lessons');document.getElementById('exam-lesson')?.scrollTo({top:0});}} aria-current={screen==='lessons'&&selected?.id===m.id?'page':undefined}><span className="exam-number">{String(examModules.indexOf(m)+1).padStart(2,'0')}</span><span>{local(m.title,language)}</span>{reviewed.includes(m.id)&&<Check size={15} aria-label={e('Reviewed','Zopakováno')}/>}</button>)}</nav>
   {!matches.length&&<p role="status">{e('No matching topics. Try another term.','Žádné odpovídající téma. Zkuste jiný výraz.')}</p>}
   <a className="exam-official" href={examUrl} target="_blank" rel="noreferrer">{e('Official assessment standard','Oficiální hodnoticí standard')}<ArrowUpRight size={16}/></a>
  </aside>
  <div className="exam-content" id="exam-lesson">
   <div hidden={screen!=='quiz'}><ExamQuiz language={language} onLesson={(id,criterion)=>{select(id);requestAnimationFrame(()=>{const target=document.getElementById(`criterion-${id}-${criterion}`);target?.scrollIntoView({block:'start'});});}}/></div>
   <div hidden={screen==='quiz'}>
   <div className="exam-scope"><BookOpen size={19}/><p>{e('13 topics · 58 criteria mapped. These original study notes and recall questions follow the NSK standard valid from 21 October 2022, checked 9 September 2026. They are an overview to extend with your course materials—not the official question bank or a substitute for supervised clinical practice.','13 témat · návaznost na 58 kritérií. Tyto vlastní studijní poznámky a otázky navazují na standard NSK platný od 21. 10. 2022, ověřený 9. 9. 2026. Jde o přehled k doplnění materiály z kurzu, nikoli oficiální banku otázek ani náhradu klinické praxe pod dohledem.')}</p></div>
   {selected?<article key={selected.id}>
    <header className="exam-heading"><span className="eyebrow mint">{e(`TOPIC ${String(index+1).padStart(2,'0')} / 13`,`TÉMA ${String(index+1).padStart(2,'0')} / 13`)}</span><h1 data-lesson-heading="true" tabIndex={-1}>{local(selected.title,language)}</h1><div className="exam-badges"><span>{local(selected.mode,language)}</span><span>{e('Criteria','Kritéria')}: {selected.sections.map(s=>s.criteria).join(', ')}</span></div></header>
    {selected.model&&<button className="exam-model-link" onClick={()=>onExplore(selected.model!)}><Focus size={20}/><span>{e('Connect this topic to the 3D atlas','Propojit téma s 3D atlasem')}<small>{e('Open related anatomy and its study note','Otevřít související anatomii a studijní poznámku')}</small></span><ChevronRight size={18}/></button>}
    <BookReading topic={selected.id} language={language}/><StudyVisuals topic={selected.id} language={language}/>
    {onPractical&&<button className="exam-model-link" onClick={onPractical}><BookOpen size={20}/><span>{e('Prepare for the practical exam','Připravit se na praktickou zkoušku')}<small>{e('12 illustrated rehearsal stations · home and supervised practice','12 ilustrovaných stanovišť · domácí nácvik a výuka pod dohledem')}</small></span><ChevronRight size={18}/></button>}
    <div className="exam-sections">{selected.sections.map(s=><section className="exam-section" id={`criterion-${selected.id}-${s.criteria}`} key={s.criteria}><div className="criterion-letter">{s.criteria}</div><div><h2>{local(s.title,language)}</h2><p>{local(s.text,language)}</p><div className="criterion-depth"><h3>{e('Reason it through','Vysvětlete souvislosti')}</h3><p>{local(criterionDepth[selected.id][s.criteria],language)}</p></div></div></section>)}</div>
    <section className="exam-case"><span className="eyebrow mint">{e('CASE REASONING','ROZVAHA NAD PŘÍPADEM')}</span><h2>{local(topicCases[selected.id].question,language)}</h2><details><summary>{e('Reveal the reasoning after answering','Po odpovědi odhalit rozvahu')}</summary><p>{local(topicCases[selected.id].answer,language)}</p></details><p className="case-pitfall"><strong>{e('Common mistake: ','Častá chyba: ')}</strong>{local(topicCases[selected.id].pitfall,language)}</p></section>
    <StudyChecklist topic={selected.id} language={language}/>
    <section className="exam-practice"><span className="eyebrow mint">{e('REHEARSE YOUR EXPLANATION','NACVIČTE SI VYSVĚTLENÍ')}</span><h2>{e('Say it, show it, justify it','Řekněte, ukažte, zdůvodněte')}</h2><p>{local(selected.practice,language)}</p></section>
    <section className="exam-recall"><h2>{e('Check your recall','Ověřte si vybavení znalostí')}</h2><p className="muted">{e('Answer aloud before opening each explanation.','Než otevřete vysvětlení, odpovězte nahlas.')}</p>{selected.quiz.map((q,i)=><details key={i}><summary><span>{local(q.question,language)}</span><ChevronRight size={17}/></summary><p>{local(q.answer,language)}</p></details>)}</section>
    <section className="exam-reading"><h2>{e('References & further reading','Zdroje a další studium')}</h2><p className="muted">{e('Sources open in their original language. Clinical techniques and device settings need your supervised course protocols. Content has not undergone independent veterinary peer review.','Zdroje se otevírají v původním jazyce. Klinické techniky a nastavení přístrojů vyžadují protokoly z výuky pod dohledem. Obsah neprošel nezávislou veterinární odbornou recenzí.')}</p>{selected.sources.map(key=>{const source=examSources[key as keyof typeof examSources];return <a key={key} href={source.url} target="_blank" rel="noreferrer">{local(source.title,language)}<ArrowUpRight size={15}/></a>;})}<a href={examUrl} target="_blank" rel="noreferrer">{e('NSK · check the exact criteria and assessment methods','NSK · ověřte přesná kritéria a způsoby ověření')}<ArrowUpRight size={15}/></a></section>
    <div className="exam-actions"><button className="exam-reviewed" disabled={!storageReady} aria-pressed={reviewed.includes(selected.id)} onClick={toggleReview}><Check size={17}/>{reviewed.includes(selected.id)?e('Reviewed · undo','Zopakováno · zrušit'):e('Mark this topic reviewed','Označit téma jako zopakované')}</button><div><button disabled={index===0} onClick={()=>select(examModules[index-1].id)} aria-label={e('Previous topic','Předchozí téma')}><ChevronLeft size={20}/></button><button disabled={index===examModules.length-1} onClick={()=>select(examModules[index+1].id)}>{e('Next topic','Další téma')}<ChevronRight size={20}/></button></div></div>
   </article>:<button className="exam-reviewed" onClick={()=>setQuery('')}>{e('Clear search','Vymazat hledání')}</button>}
   <details className="exam-rules"><summary>{e('How the assessment works','Jak probíhá ověřování')}</summary><p>{e('The standard combines written, oral and practical assessment. All criteria must be met. For the written test, the standard requires at least 70% overall and at least 50% for each criterion. These recall prompts are not a simulation of that marking system. The official standard and your authorized assessor determine the actual examination.','Standard kombinuje písemné, ústní a praktické ověřování. Je třeba splnit všechna kritéria. Písemný test vyžaduje nejméně 70 % celkem a nejméně 50 % u každého kritéria. Zdejší otázky tento způsob hodnocení nesimulují. Skutečnou zkoušku určuje oficiální standard a vaše autorizovaná osoba.')}</p></details>
   </div>
  </div>
 </section>;
}
