'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,ChevronRight,RotateCcw,BookOpen,Flag,ArrowUpRight} from 'lucide-react';
import {examModules,examSources} from './exam-data';
import {questionById,questions,type Question} from './quiz-data';
import {createRun,poolFor,quizStorageKey,readMemory,recordAnswer,scoreByTopic,submitAnswer,type Memory,type Run} from './quiz-engine';
import {photoData} from './study-visuals';
import type {Language} from './i18n';
function QuizPicture({question,language}:{question:Question;language:Language}){
 if(!question.photo)return null;const p=photoData[question.photo.kind],m=p.marks[question.photo.mark],h=1000*p.height/p.width;
 return <figure className="quiz-photo"><div className="specimen-image"><img src={'/study/'+p.file} width={p.width} height={p.height} alt={language==='cs'?'Anatomický preparát psa s jednou očíslovanou strukturou. Určete ji podle obrázku.':'Canine anatomical specimen with one numbered structure. Identify it from the image.'}/><svg viewBox={`0 0 1000 ${h}`} aria-hidden="true"><line x1={m.point[0]*1000} y1={m.point[1]*h} x2={m.label[0]*1000} y2={m.label[1]*h} stroke="#8df4dc" strokeWidth={3}/><circle cx={m.point[0]*1000} cy={m.point[1]*h} r={5} fill="#8df4dc"/><circle cx={m.label[0]*1000} cy={m.label[1]*h} r={22} fill="#153b30" stroke="#8df4dc" strokeWidth={2}/><text x={m.label[0]*1000} y={m.label[1]*h+7} textAnchor="middle" fill="#fff" fontSize={22}>{question.photo.mark+1}</text></svg></div><figcaption>Museum of Veterinary Anatomy FMVZ USP / Wagner Souza e Silva{p.editor?`; ${p.editor}`:''} · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a> · <a href={p.source} target="_blank" rel="noreferrer">{language==='cs'?'Zdroj fotografie':'Photo source'}</a>. {language==='cs'?'Přidána číslovaná vrstva; fotografie beze změn.':'Numbered overlay added; photograph unchanged.'}</figcaption></figure>;
}
export default function ExamQuiz({language,onLesson}:{language:Language;onLesson:(topic:string,criterion:string)=>void}){
 const e=(en:string,cs:string)=>language==='cs'?cs:en;
 const [mode,setMode]=useState('topics'),[topic,setTopic]=useState('all'),[limit,setLimit]=useState(10),[memory,setMemory]=useState<Memory>({}),[ready,setReady]=useState(false),[storageError,setStorageError]=useState(false),[run,setRun]=useState<Run|null>(null),[choice,setChoice]=useState(''),[unsure,setUnsure]=useState(false),[finish,setFinish]=useState(false),[endPrompt,setEndPrompt]=useState(false);
 const liveRun=useRef<Run|null>(null),liveMemory=useRef<Memory>({}),questionHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{try{const restored=readMemory(localStorage.getItem(quizStorageKey));liveMemory.current=restored;setMemory(restored);}catch{setStorageError(true);}setReady(true);},[]);
 const pool=poolFor(mode,topic,memory),reviewCount=Object.values(memory).filter(m=>m.review).length;
 const item=run?.items[run.cursor],question=item?questionById.get(item.questionId):undefined,answer=run?.answers[run.cursor];
 const module=question?examModules.find(m=>m.id===question.topic):undefined;
 useEffect(()=>{questionHeading.current?.focus({preventScroll:true});questionHeading.current?.scrollIntoView({block:'start'});},[run?.cursor,finish]);
 const start=(selectedPool=pool)=>{const next=createRun(selectedPool,limit);if(!next.items.length)return;liveRun.current=next;setRun(next);setChoice('');setUnsure(false);setFinish(false);setEndPrompt(false);};
 const check=()=>{const previous=liveRun.current;if(!previous||!choice)return;const next=submitAnswer(previous,choice,unsure);if(next===previous)return;liveRun.current=next;setRun(next);const updated=recordAnswer(liveMemory.current,next.answers[next.cursor]);liveMemory.current=updated;setMemory(updated);try{localStorage.setItem(quizStorageKey,JSON.stringify({version:1,items:updated}));setStorageError(false);}catch{setStorageError(true);}};
 const advance=()=>{if(!run||!answer)return;if(run.cursor===run.items.length-1){setFinish(true);return;}const next={...run,cursor:run.cursor+1};liveRun.current=next;setRun(next);setChoice('');setUnsure(false);document.getElementById('exam-lesson')?.scrollTo({top:0});};
 const close=()=>{liveRun.current=null;setRun(null);setFinish(false);setEndPrompt(false);setTopic('all');};
 return <section className="quiz-app" aria-label={e('Test my knowledge','Otestovat znalosti')}>
  <header className="quiz-heading"><span className="eyebrow mint">{e('RECALL · EXPLAIN · REVISIT','VYBAVIT · VYSVĚTLIT · ZOPAKOVAT')}</span><h1>{e('Test my knowledge','Otestovat znalosti')}</h1><p>{e('Original practice questions with feedback. Your results are learning signals, not an official exam result.','Vlastní procvičovací otázky se zpětnou vazbou. Výsledky ukazují, co opakovat; nejsou výsledkem oficiální zkoušky.')}</p></header>
  {storageError&&<p className="quiz-alert" role="status">{e('Saved progress is unavailable. You can practise, but this browser may not retain your revision queue.','Uložený postup není dostupný. Procvičování funguje, ale prohlížeč nemusí uchovat frontu opakování.')}</p>}
  {!run?<>
   <div className="quiz-summary"><div><strong>{questions.filter(q=>!q.photo).length}</strong><span>{e('theory questions','teoretických otázek')}</span></div><div><strong>{questions.filter(q=>q.photo).length}</strong><span>{e('picture questions','obrázkových otázek')}</span></div><div><strong>{reviewCount}</strong><span>{e('to revisit','k zopakování')}</span></div></div>
   <div className="quiz-modes" role="group" aria-label={e('Practice mode','Režim procvičování')}>{[['topics','Topic / mixed quiz','Tematický / smíšený test'],['pictures','Identify pictures','Poznávání obrázků'],['review','Revisit mistakes & doubts','Chyby a nejisté odpovědi']].map(([id,en,cs])=><button key={id} aria-pressed={mode===id} onClick={()=>{setMode(id);setTopic('all');}}>{e(en,cs)}</button>)}</div>
   <div className="quiz-setup"><label>{e('Topic','Téma')}<select value={topic} onChange={ev=>setTopic(ev.target.value)}><option value="all">{e('All topics','Všechna témata')}</option>{examModules.filter(m=>poolFor(mode,m.id,memory).length>0).map(m=><option value={m.id} key={m.id}>{m.title[language]} ({poolFor(mode,m.id,memory).length})</option>)}</select></label><label>{e('Session length','Délka procvičování')}<select value={limit} onChange={ev=>setLimit(Number(ev.target.value))}><option value={5}>{e('Up to 5 questions','Nejvýše 5 otázek')}</option><option value={10}>{e('Up to 10 questions','Nejvýše 10 otázek')}</option><option value={20}>{e('Up to 20 questions','Nejvýše 20 otázek')}</option><option value={1000}>{e('All available','Všechny dostupné')}</option></select></label></div>
   <p className="quiz-pool" aria-live="polite">{pool.length?e(`${pool.length} available · this session: ${Math.min(pool.length,limit)} questions.`,`${pool.length} dostupných · tato série: ${Math.min(pool.length,limit)} otázek.`):mode==='review'?e('Your revision queue is empty. Wrong or unsure answers appear here after a quiz.','Fronta opakování je prázdná. Po testu se zde objeví chybné a nejisté odpovědi.'):e('No questions match this selection. Choose all topics.','Výběru neodpovídají žádné otázky. Zvolte všechna témata.')}</p>
   <button className="quiz-primary" disabled={!ready||!pool.length} onClick={()=>start()}>{e('Start practice','Začít procvičování')}<ChevronRight size={18}/></button>
   <p className="quiz-storage-note">{e('Revision is saved on this device. A correct, confident retry removes a question from the queue. Current sessions are lost when reloading or leaving Exam prep; lesson links keep your session open.','Opakování se ukládá v tomto zařízení. Správná a jistá odpověď při dalším pokusu odstraní otázku z fronty. Rozpracovaná série se ztratí při obnovení stránky nebo opuštění části Ke zkoušce; odkazy na lekce ji zachovají.')}</p>
  </>:finish?<>
   <div className="quiz-result"><span>{e('SESSION RESULTS','VÝSLEDKY SÉRIE')}</span><h2 ref={questionHeading} tabIndex={-1}>{run.answers.filter(a=>a.correct).length} / {run.answers.length}</h2><p>{e(`${run.answers.length} answered of ${run.items.length} planned · ${run.answers.filter(a=>a.unsure).length} marked unsure`,`${run.answers.length} zodpovězeno z ${run.items.length} plánovaných · ${run.answers.filter(a=>a.unsure).length} označeno jako nejisté`)}</p>{run.answers.length>0&&<strong>{Math.round(100*run.answers.filter(a=>a.correct).length/run.answers.length)}%</strong>}</div>
   <h2 className="quiz-subtitle">{e('Results by topic','Výsledky podle témat')}</h2><div className="quiz-topic-results">{Object.entries(scoreByTopic(run.answers)).map(([id,s])=><div key={id}><span>{examModules.find(m=>m.id===id)!.title[language]}</span><b>{s.correct} / {s.total}</b><progress value={s.correct} max={s.total} aria-label={examModules.find(m=>m.id===id)!.title[language]}/></div>)}</div>
   <h2 className="quiz-subtitle">{e('Review your answers','Projděte si odpovědi')}</h2><div className="quiz-answer-list">{run.answers.map((a,n)=>{const q=questionById.get(a.questionId)!;return <details key={a.questionId}><summary><span className={a.correct?'quiz-good':'quiz-bad'}>{a.correct?'✓':'×'}</span><span>{n+1}. {q.prompt[language]}</span>{a.unsure&&<Flag size={15} aria-label={e('Unsure','Nejisté')}/>}</summary><p><b>{e('Your answer: ','Vaše odpověď: ')}</b>{q.choices.find(c=>c.id===a.choiceId)!.text[language]}</p><p><b>{e('Correct answer: ','Správná odpověď: ')}</b>{q.choices.find(c=>c.id===q.correctId)!.text[language]}</p><p>{q.explanation[language]}</p><button className="quiz-link" onClick={()=>onLesson(q.topic,q.criterion)}>{e('Read the lesson','Přečíst lekci')}<BookOpen size={15}/></button></details>;})}</div>
   <div className="quiz-actions"><button className="quiz-primary" onClick={()=>{const ids=new Set(run.answers.filter(a=>!a.correct||a.unsure).map(a=>a.questionId));start(questions.filter(q=>ids.has(q.id)));}} disabled={!run.answers.some(a=>!a.correct||a.unsure)}><RotateCcw size={17}/>{e('Retry missed / unsure','Znovu chybné / nejisté')}</button><button onClick={close}>{e('Choose another quiz','Vybrat jiný test')}</button></div>
  </>:question&&item?<>
   <div className="quiz-run-top"><span>{e(`Question ${run.cursor+1} of ${run.items.length}`,`Otázka ${run.cursor+1} z ${run.items.length}`)}</span><button onClick={()=>setEndPrompt(v=>!v)}>{e('End session','Ukončit sérii')}</button></div><progress className="quiz-run-progress" value={run.answers.length} max={run.items.length} aria-label={e('Questions answered','Zodpovězené otázky')}/>
   {endPrompt&&<div className="quiz-end"><p>{e('Finish now? Answered questions stay saved; unanswered questions are not scored.','Ukončit nyní? Zodpovězené otázky zůstanou uložené; nezodpovězené se nehodnotí.')}</p><button onClick={()=>{setEndPrompt(false);setFinish(true);}}>{e('Show results','Zobrazit výsledky')}</button><button onClick={()=>setEndPrompt(false)}>{e('Keep practising','Pokračovat')}</button></div>}
   <p className="quiz-topic-label">{module?.title[language]}</p><h2 className="quiz-question" ref={questionHeading} tabIndex={-1}>{question.prompt[language]}</h2>
   <QuizPicture question={question} language={language}/>
   <fieldset className="quiz-options" disabled={!!answer}><legend className="sr-only">{e('Choose one answer','Vyberte jednu odpověď')}</legend>{item.order.map((id,n)=>{const option=question.choices.find(c=>c.id===id)!;return <label key={id} className={`${choice===id?'picked':''} ${answer&&id===question.correctId?'correct':''} ${answer&&id===answer.choiceId&&!answer.correct?'incorrect':''}`}><input type="radio" name="quiz-answer" value={id} checked={choice===id} onChange={()=>setChoice(id)}/><span className="quiz-letter">{String.fromCharCode(65+n)}</span><span>{option.text[language]}</span>{answer&&id===question.correctId&&<Check size={19}/>}</label>;})}</fieldset>
   {!answer?<><label className="quiz-unsure"><input type="checkbox" checked={unsure} onChange={ev=>setUnsure(ev.target.checked)}/><Flag size={16}/>{e('I am unsure — revisit this even if correct','Nejsem si jistý/á — zopakovat i při správné odpovědi')}</label><button className="quiz-primary" disabled={!choice} onClick={check}>{e('Check answer','Ověřit odpověď')}<Check size={18}/></button></>:<div className={`quiz-feedback ${answer.correct?'success':'mistake'}`} role="status"><h3>{answer.correct?e('Correct','Správně'):e('Not quite — let’s review','Tentokrát ne — pojďme to projít')}</h3><p><b>{e('Correct answer: ','Správná odpověď: ')}</b>{question.choices.find(c=>c.id===question.correctId)!.text[language]}</p><p>{question.explanation[language]}</p><small>{!answer.correct||answer.unsure?e('Added to your revision queue.','Přidáno do fronty opakování.'):e('Correct and confident — no revision flag.','Správně a jistě — bez příznaku opakování.')}</small><div className="quiz-feedback-links"><button className="quiz-link" onClick={()=>onLesson(question.topic,question.criterion)}><BookOpen size={15}/>{e('Review this lesson','Zopakovat tuto lekci')}</button>{module&&<a href={examSources[module.sources[0] as keyof typeof examSources].url} target="_blank" rel="noreferrer">{e('Reference','Zdroj')}<ArrowUpRight size={14}/></a>}</div><button className="quiz-primary" onClick={advance}>{run.cursor===run.items.length-1?e('See results','Zobrazit výsledky'):e('Next question','Další otázka')}<ChevronRight size={18}/></button></div>}
  </>:null}
 </section>;
}
