import type {Bilingual} from './exam-data';
const b=(en:string,cs:string):Bilingual=>({en,cs});
// Original explanatory notes. Keys deliberately match the stable NSK criterion map.
export const criterionDepth:Record<string,Record<string,Bilingual>>={
 anatomy:{
  a:b('A synovial joint combines articular cartilage, a capsule and synovial fluid. Cartilage distributes compression; the capsule and ligaments constrain excessive motion. Muscle force provides dynamic stability. Describe a movement relative to the joint and anatomical plane, then distinguish a visible surface landmark from a deep attachment that cannot be directly palpated.','Synoviální kloub tvoří kloubní chrupavka, pouzdro a synoviální tekutina. Chrupavka rozkládá tlak; pouzdro a vazy omezují nadměrný pohyb. Svalová síla zajišťuje dynamickou stabilitu. Popište pohyb vzhledem ke kloubu a anatomické rovině a odlište povrchový orientační bod od hlubokého úponu, který nelze přímo nahmatat.'),
  b:b('Learn the scapular spine, acromion and olecranon as landmarks. Supraspinatus supports shoulder extension and stability; infraspinatus contributes lateral stability. Triceps extends the elbow through the olecranon, while biceps crosses shoulder and elbow. For each muscle, retrieve origin, insertion, action and innervation; a memorized name alone does not explain its mechanical role.','Naučte se hřeben lopatky, nadpažek a olekranon jako orientační body. M. supraspinatus přispívá k extenzi a stabilitě ramene, m. infraspinatus k laterální stabilitě. Triceps přes olekranon extenduje loket, biceps překlenuje rameno i loket. U každého svalu si vybavte začátek, úpon, funkci a inervaci; samotný název mechanickou úlohu nevysvětluje.'),
  c:b('The femoral head articulates with the acetabulum; the patella redirects quadriceps force. The cranial cruciate ligament limits cranial tibial translation, internal rotation and hyperextension. Gastrocnemius crosses stifle and hock, contributing to stifle flexion and hock extension. Trace these relationships on a specimen before explaining why one task can load several joints.','Hlavice femuru artikuluje s acetabulem, čéška mění směr síly kvadricepsu. Kraniální zkřížený vaz omezuje kraniální posun tibie, vnitřní rotaci a hyperextenzi. Gastrocnemius překlenuje koleno i hlezno a přispívá k flexi kolene a extenzi hlezna. Nejprve vztahy sledujte na preparátu, potom vysvětlete, proč jeden úkol zatěžuje více kloubů.'),
  d:b('Typical dogs and cats have 7 cervical, 13 thoracic, 7 lumbar and 3 fused sacral vertebrae; caudal counts vary. Atlas–axis rotation differs from movement between typical vertebrae. Intervertebral discs combine an annulus fibrosus and nucleus pulposus. Connect epaxial support, abdominal control and limb forces to trunk stability without claiming that a surface posture identifies a disc lesion.','Pes a kočka mají obvykle 7 krčních, 13 hrudních, 7 bederních a 3 srostlé křížové obratle; počet ocasních kolísá. Rotace atlas–axis se liší od pohybu mezi běžnými obratli. Meziobratlový disk tvoří anulus fibrosus a nucleus pulposus. Propojte epaxiální oporu, břišní svaly a síly končetin se stabilitou trupu; samotné držení těla neurčuje lézi disku.')
 },
 physiology:{
  a:b('Trace information from a peripheral receptor through an afferent nerve into the spinal cord, then distinguish local reflex circuitry from ascending perception and descending motor control. A motor unit is one lower motor neuron and its muscle fibres. Upper and lower motor neuron signs describe different parts of the pathway, not two degrees of the same injury.','Sledujte informaci od periferního receptoru aferentním nervem do míchy a odlište místní reflexní okruh od vzestupného vnímání a sestupného motorického řízení. Motorickou jednotku tvoří jeden dolní motoneuron a jeho svalová vlákna. Příznaky horního a dolního motoneuronu označují různé části dráhy, nikoli dvě závažnosti téhož poranění.'),
  b:b('Proprioception reports limb and joint position; vestibular input reports head movement and orientation relative to gravity. Vision also contributes to balance. Postural reactions depend on sensation, central processing and motor output, so a delayed paw replacement is not a diagnosis by itself. Compare weakness, incoordination and pain-related avoidance as different explanations for poor performance.','Propriocepce informuje o poloze končetin a kloubů, vestibulární vstup o pohybu hlavy a orientaci vůči gravitaci. K rovnováze přispívá i zrak. Posturální reakce vyžaduje čití, centrální zpracování i motorický výstup, proto opožděné přestavení tlapky samo není diagnózou. Slabost, nekoordinovanost a vyhýbání se bolesti jsou různé příčiny špatného výkonu.'),
  c:b('Depolarization propagates an action potential; acetylcholine transmits the signal at the neuromuscular junction. Calcium allows actin–myosin interaction and ATP supports cross-bridge cycling and relaxation. Isometric contraction develops force without appreciable muscle-length change; concentric shortening and eccentric lengthening differ mechanically. Electrical excitability and voluntary, coordinated movement are not interchangeable outcomes.','Depolarizace šíří akční potenciál, acetylcholin přenáší signál na nervosvalové ploténce. Vápník umožní interakci aktinu a myozinu, ATP podporuje cyklus příčných můstků i relaxaci. Izometrická kontrakce vytváří sílu bez významné změny délky svalu; koncentrické zkracování a excentrické prodlužování se mechanicky liší. Elektrická dráždivost a volní koordinovaný pohyb nejsou totožné výsledky.'),
  d:b('Immediate energy stores, anaerobic glycolysis and aerobic metabolism contribute in overlapping proportions, depending on intensity and duration. Training adaptations require recovery and task specificity. Cardiovascular fitness does not establish tendon readiness. For a sporting dog, ask about the actual event and surface; for a sedentary dog, start reasoning from its baseline function rather than an athlete’s workload.','Okamžité zásoby energie, anaerobní glykolýza a aerobní metabolismus se podílejí současně v poměru podle intenzity a délky zátěže. Tréninková adaptace potřebuje regeneraci a specifický podnět. Kardiovaskulární kondice neprokazuje připravenost šlach. U sportujícího psa zjistěte disciplínu a povrch; u nesportujícího vycházejte z jeho výchozí funkce, nikoli ze zátěže atleta.'),
  e:b('Torque depends on force and its perpendicular moment arm. A change in limb position can change joint demand even when the dog’s weight is unchanged. Ground-reaction forces act during stance; swing requires limb advancement and clearance. Compare speed, stride length and support time under consistent conditions before interpreting a change as improvement.','Moment síly závisí na síle a jejím kolmém rameni. Změna polohy končetiny může změnit nároky na kloub i při stejné hmotnosti psa. Reakční síly podložky působí v opoře, švih vyžaduje přenos končetiny a dostatečné zvednutí tlapky. Rychlost, délku kroku a dobu opory porovnávejte za stejných podmínek, teprve potom změnu označujte za zlepšení.')
 },
 healing:{
  a:b('Hemostasis, inflammation, proliferation and remodeling overlap. Early repair tissue is mechanically weaker than mature tissue even after swelling falls. Perfusion, infection, movement at the injury and systemic disease affect repair. Explain why the calendar is only one input: progression also depends on the repaired structure, fixation, veterinary restrictions and the response to the previous load.','Hemostáza, zánět, proliferace a remodelace se překrývají. Časná reparace je mechanicky slabší než zralá tkáň i po ústupu otoku. Hojení ovlivňuje prokrvení, infekce, pohyb v místě poranění a celkové onemocnění. Kalendář je jen jeden údaj: postup závisí i na struktuře, fixaci, veterinárních omezeních a reakci na předchozí zátěž.'),
  b:b('Bone may heal through primary or secondary pathways depending on stability. Tendons and ligaments remodel collagen slowly; a scar does not immediately reproduce normal tissue. Articular cartilage has limited intrinsic repair. Muscle injury can combine regeneration and fibrosis. Skin closure therefore cannot be used as evidence that deeper tendon, bone or joint tissue tolerates unrestricted exercise.','Kost se podle stability hojí primárně nebo sekundárně. Šlachy a vazy pomalu přestavují kolagen; jizva ihned nenahrazuje vlastnosti původní tkáně. Kloubní chrupavka má omezenou vlastní reparaci. Sval se hojí kombinací regenerace a fibrózy. Uzavření kůže tedy neprokazuje, že hlubší šlacha, kost nebo kloub snese neomezené cvičení.'),
  c:b('Neurapraxia is a conduction block; axonotmesis damages axons with variable preservation of supporting structures; neurotmesis disrupts the nerve more completely. Denervated muscle and skin need protection while recovery is assessed. Peripheral regeneration and central nervous system plasticity have different limits. Prognosis requires lesion-specific neurological assessment, not an assumed daily regeneration rate applied to every patient.','Neurapraxie je blok vedení; axonotmeze poškozuje axony při různém zachování podpůrných struktur; neurotmeze nerv narušuje úplněji. Denervovaný sval a kůže potřebují ochranu během hodnocení obnovy. Periferní regenerace a plasticita CNS mají jiné limity. Prognóza vyžaduje neurologické vyšetření konkrétní léze, nikoli univerzální denní rychlost regenerace pro každého pacienta.'),
  d:b('Distinguish nociceptive input, neuropathic pain and sensitization. Behaviour, function, examination and a suitable validated pain tool contribute to assessment; heart rate alone is nonspecific. Analgesia and rehabilitation work together. Record trends with the same tool and observer where possible, and report worsening function even when the animal does not vocalize.','Odlište nociceptivní vstup, neuropatickou bolest a senzitizaci. Hodnocení kombinuje chování, funkci, vyšetření a vhodnou validovanou škálu; samotná srdeční frekvence je nespecifická. Analgezie a rehabilitace se doplňují. Sledujte trend stejným nástrojem a pokud možno stejným hodnotitelem a hlaste zhoršení funkce i bez hlasových projevů bolesti.'),
  e:b('Match the intervention to a tissue problem: protect a repair, maintain permitted movement, manage swelling, preserve safe function and later restore capacity. A healing fracture and a tendon repair may require different loading limits despite similar lameness. State the restriction, the intended outcome, the measurement and the reason to pause before proposing an intervention.','Zásah přiřaďte problému tkáně: ochrana opravy, zachování povoleného pohybu, zvládání otoku, bezpečná funkce a později obnova kapacity. Hojící se zlomenina a opravená šlacha mohou potřebovat jiné limity zatížení i při podobném kulhání. Před návrhem metody uveďte omezení, zamýšlený výsledek, způsob měření a důvod k přerušení.'),
  f:b('Disuse reduces muscle capacity and joint mobility and can impair connective-tissue properties. Remobilization exposes weakened tissues to demand again; suddenly restoring the old workload can exceed their capacity. Separate cardiovascular fatigue, poor motor control and local tissue intolerance. Reassess during activity and afterward; an apparently comfortable session can still be followed by a delayed adverse response.','Nepoužívání snižuje svalovou kapacitu a pohyblivost kloubů a může zhoršit vlastnosti pojiva. Remobilizace znovu zatěžuje oslabené tkáně; náhlý návrat původní zátěže může překročit jejich možnosti. Odlište kardiovaskulární únavu, špatné motorické řízení a místní nesnášenlivost zátěže. Hodnoťte stav během aktivity i po ní; reakce může být opožděná.')
 },
 assessment:{
  a:b('Ask about onset, progression, trauma, surgery, medication, previous diagnostics, activity, environment and the owner’s priorities. Clarify which tasks changed and when. Separate an owner’s observation (“slower on stairs”) from their interpretation (“a hip problem”). Confirm current restrictions from the referring veterinarian and document unanswered questions rather than filling gaps with assumptions.','Zjišťujte začátek a vývoj potíží, úraz, operaci, léky, diagnostiku, aktivitu, prostředí a priority majitele. Upřesněte, který úkol se změnil a kdy. Oddělte pozorování majitele („pomalejší na schodech“) od jeho interpretace („problém kyčle“). Ověřte aktuální omezení u odesílajícího veterináře a nejasnosti zapište místo nahrazování domněnkami.'),
  b:b('Observe alertness, breathing, posture and interaction before touching. A general clinical screen establishes whether a focused rehabilitation assessment is appropriate. New breathing difficulty, collapse or rapidly deteriorating function changes the priority to veterinary assessment. Temperature, pulse, respiration and mucous membrane findings require correct technique and interpretation in context; excitement can alter measurements.','Než se zvířete dotknete, sledujte vědomí, dýchání, postoj a interakci. Celkový klinický screening určuje vhodnost dalšího rehabilitačního vyšetření. Nová dušnost, kolaps nebo rychlé zhoršování funkce mění prioritu na veterinární vyšetření. Teplota, pulz, dech a sliznice vyžadují správnou techniku a kontext; vzrušení může měření změnit.'),
  c:b('Use a systematic order from observation to appropriate palpation and joint assessment, comparing sides without assuming the opposite side is normal. Note pain, swelling, muscle loss, instability and movement restriction separately. Provocative instability tests require supervised clinical training and may be inappropriate after repair. A positive finding supports clinical reasoning; it does not replace the full diagnostic process.','Postupujte systematicky od pozorování k vhodné palpaci a vyšetření kloubů. Strany porovnávejte, ale nepředpokládejte zdraví druhé strany. Bolest, otok, úbytek svalů, nestabilitu a omezení pohybu zapisujte zvlášť. Provokační testy nestability vyžadují klinický výcvik pod dohledem a po opravě mohou být nevhodné. Nález podporuje rozvahu, nenahrazuje celý diagnostický proces.'),
  d:b('Organize the neurological examination around mentation, cranial nerves, posture/gait, postural reactions, spinal reflexes and sensory assessment. Localize before naming a disease. Withdrawal is a spinal reflex and does not establish conscious pain perception. Pain perception testing belongs to trained clinicians; do not practise toe pinching or forceps testing on a healthy dog.','Neurologické vyšetření členíme na vědomí, hlavové nervy, postoj a chůzi, posturální reakce, míšní reflexy a čití. Nejprve lokalizujte, potom pojmenujte nemoc. Odtahový reflex neprokazuje vědomé vnímání bolesti. Testování vnímání bolesti patří vyškoleným klinikům; na zdravém psovi nenacvičujte štípání prstů ani testy peánem.'),
  e:b('A useful baseline includes function, pain, joint motion and muscle status measured reproducibly. Specify position, landmarks, instrument, side and examiner for goniometry or girth. Girth can change with swelling as well as muscle size. Compare repeat observations under similar conditions and connect every measurement to a functional goal meaningful to the owner.','Užitečný výchozí stav zahrnuje funkci, bolest, kloubní pohyb a svaly měřené opakovatelně. U goniometrie či obvodů uveďte polohu, orientační body, přístroj, stranu a hodnotitele. Obvod se mění i s otokem, nejen s velikostí svalu. Opakujte měření za podobných podmínek a propojte je s funkčním cílem důležitým pro majitele.'),
  f:b('Record surface, speed, direction and lead handling. View the whole animal from the side, front and rear when safe, noting support duration, foot clearance, stride symmetry and trunk compensation. Head or pelvic movement can suggest unloading but cannot identify a specific lesion alone. Compare like with like: a faster second video is not a controlled reassessment.','Zaznamenejte povrch, rychlost, směr a vedení vodítka. Bezpečně sledujte celé zvíře z boku, zepředu i zezadu: dobu opory, zvedání tlapek, symetrii kroků a kompenzace trupu. Pohyb hlavy či pánve může naznačovat odlehčení, sám ale neurčí lézi. Rychlejší druhé video není srovnatelné kontrolní vyšetření.')
 },
 orthopedics:{
  a:b('Build comparison cards for elbow dysplasia/OA, shoulder tendon disorders, osteochondrosis and fractures: affected structure, typical functional problem, diagnostic evidence and restrictions. Radiographs describe structural findings, not the patient’s entire pain experience. Forelimb lameness can also originate outside the obvious joint. Use the supplied clinical report to frame rehabilitation instead of diagnosing from one photograph.','Vytvořte srovnávací karty dysplazie či OA lokte, šlachových onemocnění ramene, osteochondrózy a zlomenin: struktura, funkční problém, diagnostický podklad a omezení. Rentgen popisuje strukturu, nikoli celou bolest pacienta. Původ kulhání může ležet mimo zjevný kloub. Rehabilitaci opřete o lékařskou zprávu, ne o diagnózu z jedné fotografie.'),
  b:b('Compare cranial cruciate disease, patellar luxation, hip dysplasia/OA and fractures. A TPLO changes tibial mechanics and includes a healing osteotomy; it does not recreate the torn ligament. Patellar tracking and hip congruity pose different problems. Identify the exact operation and healing restrictions before deciding which movement or loading is permissible.','Porovnejte onemocnění kraniálního zkříženého vazu, luxaci pately, dysplazii či OA kyčle a zlomeniny. TPLO mění mechaniku tibie a zahrnuje hojící se osteotomii; neobnovuje přetržený vaz. Vedení pately a kongruence kyčle představují jiné problémy. Před volbou pohybu či zatížení zjistěte přesný výkon a omezení hojení.'),
  c:b('Start with a prioritized problem list, not a menu of modalities. Pain-limited loading, restricted joint motion and muscle weakness need different outcome measures. Explain the mechanism and limitations of each proposed intervention and why an alternative is unsuitable now. Veterinary analgesia, home footing and owner adherence may be more immediately useful than adding equipment.','Začněte seřazeným seznamem problémů, nikoli nabídkou přístrojů. Zatěžování omezené bolestí, malý rozsah kloubu a svalová slabost vyžadují jiná měřítka výsledku. U metody vysvětlete mechanismus, limity a nevhodnost alternativy v této fázi. Analgezie od veterináře, neklouzavý povrch a spolupráce majitele mohou být důležitější než další přístroj.'),
  d:b('Write a baseline, a measurable functional goal, permitted interventions, monitoring and a reassessment decision. Progress only when agreed clinical criteria are met; regress or refer when pain, swelling or function worsens. A calendar-based postoperative template must be adapted to the surgeon’s restrictions and the animal’s actual response. Include a realistic home version of the plan.','Zapište výchozí stav, měřitelný funkční cíl, povolené zásahy, sledování a rozhodnutí při kontrole. Postupujte při splnění dohodnutých klinických kritérií; při zhoršení bolesti, otoku či funkce uberte nebo pacienta odešlete. Pooperační časovou šablonu přizpůsobte chirurgickým omezením i reakci zvířete. Přidejte realistickou domácí verzi plánu.')
 },
 neurology:{
  a:b('Compare brain/vestibular presentations with spinal cord syndromes using mentation, cranial nerve signs, limb pattern and reflex findings. Disc extrusion, vascular spinal injury and degenerative disease differ in onset and management. Sudden inability to walk or progressive neurological deterioration needs prompt veterinary assessment; a rehabilitation session must not delay diagnosis.','Porovnejte mozkové a vestibulární projevy s míšními syndromy podle vědomí, hlavových nervů, postižení končetin a reflexů. Extruze disku, cévní míšní poškození a degenerativní nemoc se liší vznikem i postupem. Náhlá neschopnost chůze nebo postupné neurologické zhoršování vyžaduje rychlé veterinární vyšetření; rehabilitace nesmí zdržet diagnostiku.'),
  b:b('Peripheral nerve injury may produce weakness, reduced tone/reflexes and neurogenic muscle atrophy in a nerve distribution. Compare radial nerve dysfunction with sciatic or femoral involvement on an anatomy chart. Protect poorly controlled paws from dragging injuries. A limb’s movement alone does not establish normal sensation, and prognosis depends on the type and extent of nerve damage.','Periferní nervové poranění může způsobit slabost, snížený tonus či reflexy a neurogenní atrofii v oblasti nervu. Na schématu porovnejte radiální, sedací a femorální nerv. Chraňte špatně ovládané tlapky před poraněním při vlečení. Samotný pohyb neprokazuje normální čití a prognóza závisí na druhu a rozsahu poškození.'),
  c:b('Match assistance to remaining voluntary control and protect skin, joints and breathing. Neurological rehabilitation may combine nursing, supported task practice and prevention of secondary complications. Repetition is useful only when the task is appropriate and tolerated. Reflex-generated movement is not equivalent to recovered voluntary walking; document what the patient initiates and what the handler supplies.','Míru pomoci přizpůsobte zachovanému volnímu řízení a chraňte kůži, klouby i dýchání. Neurologická rehabilitace kombinuje ošetřování, podporovaný nácvik a prevenci komplikací. Opakování pomáhá jen u vhodného a tolerovaného úkolu. Reflexně vyvolaný pohyb není totéž jako obnovená volní chůze; zapište podíl pacienta i vedení terapeutem.'),
  d:b('Include mobility, continence, skin integrity, comfort and owner capacity in the plan. Establish how deterioration will be recognized and who to contact. Reassess neurological findings alongside function; a compensatory strategy may improve mobility without restoring the damaged pathway. Goals should remain meaningful even when complete neurological recovery is uncertain.','Do plánu zahrňte mobilitu, kontinenci, stav kůže, pohodlí a možnosti majitele. Stanovte, jak poznat zhoršení a koho kontaktovat. Neurologický nález kontrolujte spolu s funkcí; kompenzace může zlepšit mobilitu bez obnovy poškozené dráhy. Cíle mají mít význam i při nejisté úplné neurologické obnově.')
 },
 passive:{
  a:b('Passive movement is supplied externally and does not provide the same strengthening stimulus as active muscle work. State whether the goal is maintaining comfortable motion, assessing range or addressing a specific soft-tissue limitation. Pain, instability, repair restrictions and animal consent constrain the technique. A normal healthy joint does not need forced extra range for exam practice.','Pasivní pohyb dodává vnější síla a neposkytuje stejný posilovací podnět jako aktivní práce. Uveďte, zda udržujete komfortní pohyb, měříte rozsah nebo řešíte konkrétní měkkotkáňové omezení. Techniku limitují bolest, nestabilita, omezení po opravě a ochota zvířete. Zdravý kloub nepotřebuje při nácviku zkoušky násilně větší rozsah.'),
  b:b('PROM moves a joint through an allowed range; stretching targets tissue length, and goniometry measures an angle. These are separate tasks. Reproducible goniometry needs a defined animal position, joint centre and limb landmarks, with adjacent motion controlled. Learn hand placement and end-feel under supervision; do not force an angle to match a textbook reference value.','PROM vede kloub povoleným rozsahem, strečink cílí na délku tkáně a goniometrie měří úhel. Jde o různé úkoly. Opakovatelná goniometrie vyžaduje danou polohu, střed kloubu a orientační body končetiny s kontrolou sousedního pohybu. Úchopy a koncový pocit se učte pod dohledem; nevynucujte úhel podle tabulky.'),
  c:b('Joint mobilization addresses accessory movement such as glide or distraction, rather than simply repeating flexion and extension. Direction and grade depend on joint anatomy, clinical assessment and tissue irritability. Instability and healing repairs can make mobilization inappropriate. Rehearse terminology and joint-surface relationships on a model; clinical hand placement and force require instructor feedback.','Mobilizace řeší přídatný pohyb, například skluz či distrakci, nikoli jen opakování flexe a extenze. Směr a stupeň závisejí na anatomii, vyšetření a dráždivosti tkáně. Nestabilita a hojící se oprava mohou mobilizaci vylučovat. Pojmy a vztahy kloubních ploch nacvičujte na modelu; úchop a síla potřebují zpětnou vazbu instruktora.'),
  d:b('Distinguish superficial contact, effleurage and kneading by their intended tissue effect, contact and pressure. The animal’s response is part of assessment, not an obstacle to overcome. Avoid assuming deeper pressure is more effective. Painful, infected, injured or medically unexplained areas need assessment before treatment; evidence and technique-specific limitations should be stated honestly.','Odlište povrchový kontakt, effleurage a hnětení podle zamýšleného účinku, kontaktu a tlaku. Reakce zvířete patří k hodnocení, není překážkou k překonání. Vyšší tlak automaticky neznamená vyšší účinnost. Bolestivá, infikovaná, poraněná či neobjasněná oblast potřebuje před ošetřením vyšetření; uvádějte i limity důkazů a techniky.')
 },
 active:{
  a:b('Choose a task for a defined impairment and functional goal. Assistance, surface, speed, duration and complexity all change demand. Increase one relevant variable at a time after reassessment so the reason for a change is interpretable. Movement quality and recovery matter more than completing an arbitrary number of repetitions. Strength, endurance and coordination are related but distinct targets.','Úkol vybírejte podle konkrétní poruchy a funkčního cíle. Náročnost mění pomoc, povrch, rychlost, délka i složitost. Po kontrole upravujte jednu podstatnou proměnnou, aby bylo možné vyhodnotit příčinu změny. Kvalita pohybu a zotavení jsou důležitější než libovolný počet opakování. Síla, vytrvalost a koordinace jsou související, ale různé cíle.'),
  b:b('Assisted standing should supply only the support the patient needs, without suspending or twisting the animal. Unstable surfaces and raised poles change balance and limb-clearance demands; they are not universally gentle beginner exercises. A suitable stable-surface task may be the correct first choice. Learn guarding, support placement and progression with an instructor and a screened patient.','Asistovaný stoj má poskytovat jen potřebnou oporu bez zavěšení či kroucení zvířete. Nestabilní povrchy a zvýšené tyče mění nároky na rovnováhu a zvedání končetin; nejsou univerzálně lehkým začátkem. Správnou první volbou může být stabilní podložka. Jištění, polohu podpory a postup se učte s instruktorem u vyšetřeného pacienta.'),
  c:b('A spinal reflex can generate movement through a local circuit without a voluntary command. Explain the afferent limb, integration and efferent limb, then distinguish eliciting a response from achieving useful function. Selection and handling depend on the neurological lesion and contraindications. This is a supervised clinical skill, not a home experiment with startling or painful stimuli.','Míšní reflex vytváří pohyb místním okruhem bez volního povelu. Vysvětlete aferentní část, integraci a eferentní část a odlište vyvolání reakce od užitečné funkce. Volba a provedení závisejí na neurologické lézi a kontraindikacích. Jde o klinickou dovednost pod dohledem, nikoli domácí pokus s lekáním či bolestivými podněty.'),
  d:b('Task examples include controlled walking and selected transitions, but their suitability depends on the patient. A sit-to-stand can expose asymmetrical loading, yet repeated poor transitions may rehearse compensation. Define the desired quality, permitted assistance, rest and stop criteria before prescribing. Do not use food lures to push a dog through pain or fatigue.','Příklady úkolů jsou řízená chůze a vybrané přechody poloh, vhodnost ale závisí na pacientovi. Přechod sed–stoj může ukázat asymetrii, opakování špatných přechodů však upevňuje kompenzaci. Před předepsáním určete kvalitu, povolenou pomoc, odpočinek a důvody ukončení. Pamlskem nepřemáhejte bolest nebo únavu psa.')
 },
 modalities:{
  a:b('Heat and cold alter tissue temperature and physiological responses; depth and duration depend on the application. A barrier, skin checks and intact sensation matter because thermal injury can occur without an obvious protest. Match the choice to tissue state and circulation. Rehearse indications, contraindications and monitoring rather than memorizing one pack duration for all animals.','Teplo a chlad mění teplotu tkání a fyziologické reakce; hloubka a trvání účinku závisejí na aplikaci. Důležitá je bariéra, kontrola kůže a zachované čití, protože tepelné poškození nemusí vyvolat zjevný protest. Volbu přizpůsobte stavu tkáně a cirkulace. Učte se indikace, kontraindikace a sledování místo jediné doby aplikace pro všechna zvířata.'),
  b:b('Pulsed electromagnetic field devices expose tissue to changing fields; they are not interchangeable with static magnets or every form of magnetic stimulation. Field characteristics and evidence vary between devices and conditions. Explain the proposed biological target, study limitations, implant considerations and manufacturer restrictions. A device’s availability does not establish a clinical indication.','Přístroje pulzního elektromagnetického pole působí proměnlivým polem; nejsou zaměnitelné se statickými magnety ani každou magnetickou stimulací. Parametry i důkazy se mezi přístroji a diagnózami liší. Vysvětlete zamýšlený biologický cíl, limity studií, význam implantátů a omezení výrobce. Dostupnost přístroje sama není indikací.'),
  c:b('Therapeutic ultrasound uses acoustic energy. Frequency, intensity, duty cycle, treatment area and coupling affect delivery; diagnostic ultrasound serves a different purpose. Poor coupling or inappropriate application can cause harm. Identify the transducer and coupling medium on equipment images, then explain why tissue depth and clinical condition must guide a trained operator’s protocol.','Terapeutický ultrazvuk využívá akustickou energii. Dodávku ovlivňuje frekvence, intenzita, pracovní cyklus, plocha a vazební prostředí; diagnostický ultrazvuk má jiný účel. Špatný kontakt či nevhodná aplikace mohou škodit. Na obrázku určete hlavici a vazební médium a vysvětlete, proč protokol vyškoleného pracovníka závisí na hloubce a stavu tkáně.'),
  d:b('TENS primarily targets pain modulation; NMES seeks muscle activation. Electrode placement, skin integrity, sensation and nerve/muscle status matter. A visible contraction does not prove suitable functional loading. Keep electrical stimulation distinct from magnetic stimulation and clarify the FMS terminology with your course provider. Device settings must follow patient assessment and the specific equipment protocol.','TENS cílí především na modulaci bolesti, NMES na aktivaci svalu. Záleží na elektrodách, kůži, čití a stavu nervu i svalu. Viditelná kontrakce nedokazuje vhodné funkční zatížení. Elektrickou a magnetickou stimulaci rozlišujte a pojem FMS ověřte ve výuce. Nastavení musí odpovídat vyšetření pacienta a konkrétnímu přístroji.'),
  e:b('Photobiomodulation uses light with effects influenced by wavelength, power, dose, tissue and application. Appropriate eye protection for the device is essential for everyone exposed, including the animal. Power alone is not a dose; exposure area and time matter. Evidence for one condition or device cannot automatically be generalized to another.','Fotobiomodulace využívá světlo, jehož účinek ovlivňuje vlnová délka, výkon, dávka, tkáň a aplikace. Ochrana očí odpovídající přístroji je zásadní pro všechny vystavené osoby i zvíře. Výkon sám není dávka; záleží na ploše a čase. Důkazy pro jednu diagnózu či přístroj nelze automaticky přenést na jiné.'),
  f:b('Shockwave delivers mechanical pressure waves; focused and radial systems differ in energy delivery. It is not the same intervention as therapeutic ultrasound. Patient selection, localization, analgesia/sedation needs and equipment-specific precautions require veterinary planning. Explain the target tissue and outcome to monitor, and avoid presenting temporary pain reduction as proof that tissue can tolerate unrestricted activity.','Rázová vlna dodává mechanické tlakové vlny; fokusované a radiální systémy se liší přenosem energie. Nejde o stejnou metodu jako terapeutický ultrazvuk. Výběr pacienta, lokalizace, analgezie či sedace a bezpečnost přístroje vyžadují veterinární plán. Vysvětlete cílovou tkáň a sledovaný výsledek; dočasný ústup bolesti nedokazuje připravenost na neomezenou zátěž.')
 },
 hydrotherapy:{
  a:b('Buoyancy reduces effective loading while viscosity resists movement; hydrostatic pressure acts around immersed tissue. Water depth changes both support and movement demand. Swimming and underwater treadmill walking have different limb patterns and control options. Cardiopulmonary tolerance, wounds, infection risks and fear influence suitability. Hydrotherapy is not automatically easier or safer because the animal weighs less in water.','Vztlak snižuje účinné zatížení, viskozita klade pohybu odpor a hydrostatický tlak působí na ponořenou tkáň. Hloubka mění oporu i nároky pohybu. Plavání a chůze na podvodním pásu mají jiné vzorce a možnosti řízení. Vhodnost ovlivňují srdce a plíce, rány, infekce i strach. Menší zatížení ve vodě automaticky neznamená snazší či bezpečnější úkol.'),
  b:b('Plan entry, exit, acclimatization, non-slip footing, assistance and emergency removal before treatment. Observe breathing, posture, fatigue and willingness throughout, with attention to water hygiene and temperature. A flotation aid does not eliminate drowning risk. Practise a dry verbal equipment-and-emergency briefing for the exam; a home bath or pool is not a substitute for supervised hydrotherapy training.','Před terapií naplánujte vstup, výstup, zvykání, neklouzavý povrch, pomoc a nouzové vyjmutí. Průběžně sledujte dech, postoj, únavu a ochotu i hygienu a teplotu vody. Plovací pomůcka nevylučuje utonutí. Ke zkoušce nacvičte slovní popis vybavení a nouzového postupu nasucho; domácí vana či bazén nenahrazuje výcvik hydroterapie pod dohledem.')
 },
 support:{
  a:b('Record voluntary urination/defecation, accidents, skin soiling and changes in urine. Wet bedding does not prove the bladder empties adequately; overflow can occur. Bladder management depends on neurological and urinary assessment. Learn prescribed techniques directly from the veterinary team; never practise expression on a healthy dog. Straining without urine or apparent discomfort warrants prompt veterinary contact.','Zaznamenávejte volní močení a kálení, nehody, znečištění kůže a změny moči. Mokré lůžko neprokazuje vyprázdnění měchýře; může jít o přetékání. Postup závisí na neurologickém a urologickém vyšetření. Předepsané techniky se učte přímo od veterinárního týmu; expresi nenacvičujte na zdravém psovi. Tlačení bez moči či diskomfort vyžadují rychlý kontakt s veterinářem.'),
  b:b('A sling, harness, ramp or cart should solve a defined mobility problem and fit the animal and home. Check pressure points, skin, breathing, toileting clearance and the owner’s handling ability. An aid can introduce falls or rubbing if poorly fitted. Fit and reassessment are part of treatment, not optional extras after choosing a product.','Závěs, postroj, rampa či vozík má řešit konkrétní problém mobility a odpovídat zvířeti i domácnosti. Kontrolujte tlaková místa, kůži, dech, prostor pro vylučování a schopnost majitele pomůcku používat. Špatně padnoucí pomůcka může způsobit pád či oděrky. Nasazení a kontrola patří k terapii, nejsou doplňkem po výběru výrobku.'),
  c:b('An orthosis supports or modifies an existing body segment; a prosthesis replaces a missing segment. Bandages can provide protection or support but can also impair circulation and damage skin. Prescription, fitting and follow-up depend on the condition. Rehearse material recognition and warning signs on a model; do not wrap a healthy limb tightly as home practice.','Ortéza podpírá nebo ovlivňuje přítomný tělesný segment, protéza nahrazuje chybějící část. Bandáž chrání či podporuje, ale může poškodit kůži a cirkulaci. Indikace, nasazení a kontrola závisejí na onemocnění. Materiály a varovné příznaky nacvičujte na modelu; zdravou končetinu doma pevně neobvazujte.'),
  d:b('Assess body weight, body condition and muscle condition separately; an overweight patient can also have substantial muscle loss. Ask about complete diet, treats and supplements before discussing energy balance with the veterinary team. Nutritional support and weight management must preserve muscle and account for disease. Chondroprotective products vary in evidence and do not replace analgesia or appropriate rehabilitation.','Hmotnost, tělesnou kondici a osvalení hodnoťte odděleně; i obézní pacient může mít výrazný úbytek svalů. Před řešením energetické bilance s veterinářem zjistěte celou stravu, pamlsky a doplňky. Výživa a redukce hmotnosti musí chránit svaly a zohlednit nemoci. Důkazy pro chondroprotektiva se liší; nenahrazují analgezii ani vhodnou rehabilitaci.'),
  e:b('Palliative goals prioritize comfort, valued activities, access to food/water and tolerable nursing. Track good and difficult days and agree on signs that require plan review. Burdensome treatment may be inappropriate even if technically possible. Discuss quality of life with the veterinary team and owner, respecting the animal’s preferences and the caregiver’s capacity.','Paliativní cíle upřednostňují pohodlí, oblíbené činnosti, přístup ke krmivu a vodě a snesitelné ošetřování. Sledujte dobré i obtížné dny a domluvte signály ke změně plánu. Zatěžující léčba nemusí být vhodná, i když je technicky možná. Kvalitu života řešte s veterinářem a majitelem při respektování zvířete i možností pečujícího.')
 },
 cases:{
  a:b('Separate observations, interpretations and unresolved questions. Prioritize threats to welfare and tissue safety before performance goals. A problem list might include pain-limited loading, difficulty rising and a slippery home floor; these require different responses. State what evidence supports each conclusion and which findings need veterinary clarification before treatment.','Oddělte pozorování, interpretace a nevyřešené otázky. Před výkonovými cíli řešte welfare a bezpečí tkání. Seznam problémů může zahrnovat zatížení omezené bolestí, obtížné vstávání a kluzkou podlahu; každá položka potřebuje jinou reakci. U závěrů uveďte důkazy a nálezy vyžadující veterinární objasnění před terapií.'),
  b:b('Extract diagnosis, side, procedure/date, imaging conclusions, medication, comorbidities and explicit restrictions from a report. Translate jargon into functional consequences without inventing missing instructions. “Postoperative” is insufficient: identify what was repaired and how it is protected. Contact the referring team when the report conflicts with the owner’s account or today’s clinical findings.','Ze zprávy vyberte diagnózu, stranu, výkon a datum, závěry zobrazování, léky, další nemoci a omezení. Odborné pojmy převeďte na funkční důsledky bez domýšlení pokynů. „Po operaci“ nestačí: zjistěte opravenou strukturu a její ochranu. Při rozporu zprávy s majitelem či dnešním nálezem kontaktujte odesílající tým.'),
  c:b('Use a problem → goal → intervention → measurement → review chain. Specify who performs each task and under what restrictions, with a clear response to deterioration. A useful protocol can explain why an intervention is withheld as well as why one is chosen. Progression should follow clinical response and reassessment, not simply completion of scheduled sessions.','Použijte řetězec problém → cíl → zásah → měření → kontrola. Uveďte vykonavatele a omezení každého úkolu i reakci na zhoršení. Dobrý protokol vysvětluje i důvod neprovedení metody. Postup má vycházet z klinické reakce a kontrolního vyšetření, nikoli pouze z absolvování naplánovaných návštěv.'),
  d:b('Demonstrate the agreed task, then ask the owner to show and explain it back. Give a short written plan with setup, permitted activity, monitoring, stop signs and contact details. Check the home environment and practical constraints. “Do you understand?” gives less evidence of learning than seeing the owner perform a safe teach-back.','Předveďte dohodnutý úkol a požádejte majitele, aby jej ukázal a vysvětlil zpět. Krátký písemný plán má obsahovat přípravu, povolenou aktivitu, sledování, důvody ukončení a kontakt. Ověřte prostředí a praktické možnosti doma. Otázka „Rozumíte?“ prokazuje naučení méně než bezpečné zpětné předvedení majitelem.')
 },
 special:{
  a:b('For obesity with OA, coordinate pain care, nutrition, environmental changes and tolerable activity. Weight loss and muscle preservation are complementary goals; forced exercise through pain is counterproductive. Track body condition, muscle condition and meaningful daily tasks. Cats may reveal difficulty through reduced jumping, grooming or social activity rather than obvious limping.','U obezity s OA propojte péči o bolest, výživu, úpravu prostředí a tolerovanou aktivitu. Redukce hmotnosti a ochrana svalů se doplňují; nucený pohyb přes bolest škodí. Sledujte tělesnou i svalovou kondici a běžné úkoly. U koček mohou potíže ukazovat menší skákání, péče o srst či sociální aktivita místo zjevného kulhání.'),
  b:b('Age alone is not a diagnosis. Screen for pain, muscle loss, sensory change, cognitive change and other disease. Improve access and footing while preserving activities the animal enjoys. Shorter, well-tolerated tasks may suit an individual better than long sessions. Reassess regularly because several conditions can change together and conceal the reason for declining function.','Samotný věk není diagnóza. Posuzujte bolest, úbytek svalů, změny smyslů a kognice i další nemoci. Zlepšete přístupnost a povrchy při zachování oblíbených činností. Konkrétnímu zvířeti mohou více vyhovovat kratší tolerované úkoly než dlouhé jednotky. Pravidelně kontrolujte stav, protože souběžné nemoci mohou zakrýt příčinu zhoršení funkce.'),
  c:b('Critical illness places medical stabilization, oxygen delivery and organ support ahead of exercise goals. Positioning, skin protection and selected movement must be coordinated with the treating team around monitoring, lines and restrictions. Do not transfer a routine orthopedic program to an unstable patient. Explain which clinical changes would stop a session and require immediate team review.','V kritickém stavu mají stabilizace, dodávka kyslíku a podpora orgánů přednost před cvičebními cíli. Polohování, ochranu kůže a vybraný pohyb koordinujte s týmem podle monitorace, vstupů a omezení. Běžný ortopedický program nepřenášejte na nestabilního pacienta. Vysvětlete změny vyžadující ukončení a okamžité přehodnocení týmem.'),
  d:b('Cardiac disease varies widely in severity and exercise tolerance. Obtain the treating veterinarian’s activity guidance and monitoring plan rather than using a universal heart-rate target. New breathing difficulty, collapse or marked exercise intolerance warrants stopping and veterinary assessment. Water immersion and physical exertion can alter cardiovascular demand, so hydrotherapy also needs individual consideration.','Srdeční onemocnění se výrazně liší závažností i tolerancí zátěže. Vyžádejte si pokyny ošetřujícího veterináře a plán sledování místo univerzální cílové tepové frekvence. Nová dušnost, kolaps či výrazná nesnášenlivost zátěže vyžadují ukončení a veterinární vyšetření. Ponoření i námaha mění kardiovaskulární nároky, proto i hydroterapie potřebuje individuální posouzení.')
 }
};

export const topicCases:Record<string,{question:Bilingual;answer:Bilingual;pitfall:Bilingual}>={
 anatomy:{question:b('Why is pointing at the outside of a stifle not the same as identifying a cruciate ligament?','Proč ukázání na povrch kolene není totéž jako identifikace zkříženého vazu?'),answer:b('The ligament lies deep within the joint. Identify its bone attachments on a specimen or diagram, explain its stabilizing action, and use the live dog only to indicate the joint region. State the limits of surface palpation and of the schematic atlas guide.','Vaz leží hluboko v kloubu. Na preparátu či schématu určete kostní úpony, vysvětlete stabilizační funkci a na živém psovi ukažte jen oblast kloubu. Uveďte limity povrchové palpace i schematické značky atlasu.'),pitfall:b('Confusing tendons, ligaments and menisci.','Záměna šlach, vazů a menisků.')},
 physiology:{question:b('A dog can move a leg when stimulated but cannot place it accurately. What remains unknown?','Pes při podnětu pohne nohou, ale neumí ji přesně umístit. Co zůstává nejasné?'),answer:b('Movement alone does not establish normal sensation, voluntary control or coordination. Describe the sensory–central–motor pathway and request neurological localization. Distinguish a reflex response from a purposeful task.','Pohyb sám neprokazuje normální čití, volní řízení ani koordinaci. Popište senzorickou–centrální–motorickou dráhu a potřebu neurologické lokalizace. Odlište reflexní reakci od cíleného úkolu.'),pitfall:b('Calling every movement recovery.','Označení každého pohybu za obnovu funkce.')},
 healing:{question:b('The skin incision is closed after tendon repair. Can the dog return to unrestricted play?','Kůže po opravě šlachy je uzavřená. Může se pes neomezeně hrát?'),answer:b('Skin closure does not establish tendon strength. Check the procedure, healing status and surgeon’s restrictions. Explain collagen remodeling and the need for controlled, individually progressed loading with reassessment.','Uzavření kůže neprokazuje pevnost šlachy. Ověřte výkon, stav hojení a omezení chirurga. Vysvětlete přestavbu kolagenu a potřebu řízené individuálně stupňované zátěže s kontrolami.'),pitfall:b('Using time since surgery as the only progression criterion.','Postup pouze podle času od operace.')},
 assessment:{question:b('The second gait video looks more symmetrical, but the dog walks faster. Is improvement established?','Druhé video vypadá symetričtěji, pes ale jde rychleji. Je prokázáno zlepšení?'),answer:b('No. Speed is a confounder. Repeat comparable observations on the same surface with similar speed, camera position and lead handling, and combine gait with pain and functional measures. Record uncertainty.','Ne. Rychlost zkresluje srovnání. Opakujte záznam na stejném povrchu při podobné rychlosti, poloze kamery a vedení. Chůzi spojte s hodnocením bolesti a funkce a zapište nejistotu.'),pitfall:b('Diagnosing a lesion from a single gait sign.','Diagnóza léze z jediného příznaku chůze.')},
 orthopedics:{question:b('Two dogs limp after different stifle operations. Should their home plans be identical?','Dva psi kulhají po různých operacích kolene. Mají mít stejný domácí plán?'),answer:b('No. Identify the repaired structures, any osteotomy, fixation and explicit restrictions. Build goals from each examination and owner context, then explain monitoring and progression criteria.','Ne. Zjistěte opravené struktury, osteotomii, fixaci a výslovná omezení. Cíle odvoďte z jednotlivého vyšetření a možností majitele a vysvětlete sledování a kritéria postupu.'),pitfall:b('Selecting treatment from the diagnosis label alone.','Výběr terapie jen podle názvu diagnózy.')},
 neurology:{question:b('A nonambulatory dog has wet bedding. What must be checked before calling it normal urination?','Nechodící pes má mokré lůžko. Co ověřit před označením močení za normální?'),answer:b('Determine whether urination is voluntary and bladder emptying adequate through veterinary assessment; leakage may be overflow. Include skin protection, nursing and a bladder plan. Do not try expression as a diagnostic experiment.','Veterinárně ověřte volní močení a dostatečné vyprázdnění; únik může být přetékání. Zahrňte ochranu kůže, ošetřování a plán měchýře. Expresi nezkoušejte jako diagnostický pokus.'),pitfall:b('Equating withdrawal with conscious pain perception.','Záměna odtahového reflexu za vědomé vnímání bolesti.')},
 passive:{question:b('A measured range is smaller than a book’s reference. Should you push farther?','Naměřený rozsah je menší než v knize. Máte zatlačit dál?'),answer:b('No. Check positioning and landmarks, pain, restrictions and tissue response. Reference values are not targets to force. Discuss repeatability and seek instructor guidance on examination and technique.','Ne. Zkontrolujte polohu, body, bolest, omezení a reakci tkáně. Referenční hodnoty nejsou cíle k vynucení. Posuďte opakovatelnost a techniku konzultujte s instruktorem.'),pitfall:b('Treating passive movement as strengthening.','Považování pasivního pohybu za posilování.')},
 active:{question:b('A dog completes every repetition but shifts away from one hindlimb. Is the exercise successful?','Pes dokončí všechna opakování, ale odlehčuje jednu pánevní končetinu. Je cvičení úspěšné?'),answer:b('Completion alone is insufficient. Stop or modify according to the plan and reassess pain, support and task difficulty. Describe the desired movement quality and avoid practising a compensation simply to achieve a number.','Dokončení nestačí. Podle plánu přerušte či upravte úkol a posuďte bolest, oporu a náročnost. Popište požadovanou kvalitu a neupevňujte kompenzaci kvůli počtu opakování.'),pitfall:b('Increasing speed, instability and duration together.','Současné zvýšení rychlosti, nestability a délky.')},
 modalities:{question:b('An examiner shows two devices with different power ratings. Does higher power mean a better treatment?','Zkoušející ukáže dva přístroje s různým výkonem. Znamená vyšší výkon lepší terapii?'),answer:b('No. Identify the energy type, target, dose variables, evidence and precautions. Power alone does not describe tissue dose or suitability. Explain why the patient and device protocol determine selection.','Ne. Určete druh energie, cíl, dávkovací proměnné, důkazy a opatření. Výkon sám neurčuje dávku v tkáni ani vhodnost. Volba závisí na pacientovi a protokolu přístroje.'),pitfall:b('Memorizing universal settings without patient context.','Univerzální nastavení bez kontextu pacienta.')},
 hydrotherapy:{question:b('A dog refuses to enter the tank. Should it be lifted in to begin acclimatization?','Pes odmítá vstoupit do nádrže. Má být zvednut dovnitř, aby si začal zvykat?'),answer:b('Do not force the session. Reassess fear, pain, entry footing and suitability. Describe voluntary acclimatization and the trained team’s entry and emergency plan. Welfare is part of the outcome.','Jednotku nevynucujte. Posuďte strach, bolest, povrch vstupu a vhodnost. Popište dobrovolné zvykání a plán vstupu i nouze vyškoleného týmu. Welfare je součást výsledku.'),pitfall:b('Assuming swimming and underwater walking are interchangeable.','Záměna plavání a podvodní chůze.')},
 support:{question:b('A support harness improves walking but leaves a red area. What changes?','Podpůrný postroj zlepší chůzi, ale zanechá zarudnutí. Co se mění?'),answer:b('Stop use and assess skin and fit with the prescribing team before continuing. A mobility benefit does not justify pressure injury. Review support location, duration, hygiene and owner checks.','Použití přerušte a před pokračováním s týmem posuďte kůži a velikost. Lepší mobilita neospravedlňuje otlak. Zkontrolujte místo podpory, délku, hygienu a kontroly majitelem.'),pitfall:b('Ignoring caregiver capacity and skin checks.','Opomenutí možností pečujícího a kontroly kůže.')},
 cases:{question:b('The owner agrees with your explanation. How do you check that the home task is understood?','Majitel s vysvětlením souhlasí. Jak ověříte porozumění domácímu úkolu?'),answer:b('Use teach-back: ask them to demonstrate setup and the agreed task, explain stop signs and state who they would contact. Correct misunderstandings, simplify the written plan and document the agreed version.','Použijte zpětné předvedení: majitel ukáže přípravu a úkol, vysvětlí důvody přerušení a uvede kontakt. Opravte nejasnosti, zjednodušte písemný plán a zapište dohodnutou verzi.'),pitfall:b('Writing a list of treatments without measurable goals.','Seznam metod bez měřitelných cílů.')},
 special:{question:b('An older cat stops jumping onto its usual chair. Is this simply normal aging?','Starší kočka přestala skákat na oblíbenou židli. Je to jen normální stárnutí?'),answer:b('No. Seek assessment for pain, mobility change and other disease. Discuss accessible resources and low-stress observation, then set individualized comfort and function goals. Do not copy a dog exercise prescription to a cat.','Ne. Je třeba posoudit bolest, změnu mobility a jiné nemoci. Proberte dostupné zdroje a pozorování bez stresu a stanovte individuální cíle pohodlí a funkce. Psí předpis nepřenášejte na kočku.'),pitfall:b('Attributing a new symptom to age without assessment.','Připsání nového příznaku věku bez vyšetření.')}
};
