'use client';
import {sitePath} from './site-path';
import {useEffect,useState} from 'react';
import books from './library-data.json';
import {type Language} from './i18n';
export default function Library({language}:{language:Language}){
 const e=(en:string,cs:string)=>language==='cs'?cs:en;
 const [selected,setSelected]=useState<string|null>(null),[part,setPart]=useState(0);
 const [requestedPage,setRequestedPage]=useState<number|null>(null);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),b=books.find(b=>b.id===params.get('book')),page=Number(params.get('page'));if(b){setSelected(b.id);const valid=Number.isInteger(page)&&page>=1&&page<=b.pages?page:1;setPart(b.parts.findIndex(p=>valid>=p.start&&valid<=p.end));setRequestedPage(valid);}},[]);
 const book=books.find(b=>b.id===selected),section=book?.parts[part];
 return <section className="book-library"><header><span className="eyebrow mint">{e('YOUR BOOKS','TVOJE KNIHY')}</span><h2>{e('Reading library','Knihovna')}</h2><p>{e('Choose a book to read. PDFs retain their original English text.','Vyber knihu ke čtení. PDF zachovávají původní anglický text.')}</p></header>
 {!book?<div className="book-grid">{books.map((b,i)=><article key={b.id} className="book-card"><span className="book-number">0{i+1}</span><small>{i===2?e('ASTROPHYSICS','ASTROFYZIKA'):e('VETERINARY REHABILITATION','VETERINÁRNÍ REHABILITACE')}</small><h3>{b.title}</h3><p>{b.author}</p><p>{b.pages} {e('PDF pages · English','stran PDF · anglicky')}</p><button className="primary" onClick={()=>{setSelected(b.id);setPart(0);setRequestedPage(null);}}>{e('Read book','Číst knihu')} →</button></article>)}</div>:section&&<div className="book-reader"><button className="book-back" onClick={()=>setSelected(null)}>← {e('All books','Všechny knihy')}</button><h3>{book.title}</h3><p>{book.author}</p><div className="book-toolbar"><button disabled={part===0} onClick={()=>{setPart(p=>p-1);setRequestedPage(null);}}>{e('Previous section','Předchozí část')}</button><label>{e('PDF page range','Rozsah stran PDF')}<select value={part} onChange={ev=>{setPart(Number(ev.target.value));setRequestedPage(null);}}>{book.parts.map((p,i)=><option key={p.url} value={i}>{p.start}–{p.end} / {book.pages}</option>)}</select></label><button disabled={part===book.parts.length-1} onClick={()=>{setPart(p=>p+1);setRequestedPage(null);}}>{e('Next section','Další část')}</button><a href={sitePath(section.url)+'#page='+((requestedPage??section.start)-section.start+1)} target="_blank" rel="noreferrer">{e('Open PDF separately','Otevřít PDF samostatně')} ↗</a></div>{requestedPage&&<p className="book-page-target">{e('Opening PDF page','Otevírá se strana PDF')} <strong>{requestedPage}</strong> · {e('Page within this section','Strana v této části')}: {requestedPage-section.start+1}</p>}<p className="book-help">{e('Page ranges follow the PDF file, including cover and front matter; printed page numbers may differ. Use the PDF toolbar to zoom or search this section. If the embedded reader is unavailable, open the PDF separately.','Rozsahy odpovídají stranám souboru PDF včetně obálky a úvodních stran; tištěné číslování se může lišit. Lišta PDF umožňuje přiblížení a hledání v této části. Pokud se vložená čtečka nezobrazí, otevři PDF samostatně.')} ({Math.ceil(section.bytes/1048576)} MB)</p><iframe key={section.url} src={sitePath(section.url)+'#page='+((requestedPage??section.start)-section.start+1)+'&view=FitH'} title={`${book.title} · ${section.start}–${section.end}`} className="book-frame"/></div>}
 </section>;
}
