import type {Atlas,Part} from './anatomy';
import type {Language} from './i18n';
type Pair=[string,string];
type Guide={key:string;name:Pair;region:string;points:number[][];attachments:Pair;action:Pair;relevance:Pair;recall:Pair;lab:string;bilateral:boolean};
// Approximate attachment regions in the source reference pose; never measured anatomy.
// Endpoints are placed on nearby source bone vertices; anatomical footprints remain approximate.
// Negative Z is the left side. Right-side guides mirror this symmetric source model.
const guides:Guide[]=[
 {key:'cranial_cruciate',name:['Cranial cruciate ligament','Zkřížený vaz kraniální'],region:'Hindlimb',points:[[-.35503,.30994,-.07777],[-.36032,.29849,-.07350],[-.36562,.28704,-.06922]],attachments:['Caudomedial surface of the lateral femoral condyle → cranial intercondylar area of the tibia. Intracapsular but extrasynovial; its two functional bundles are not separated here.','Kaudomediální plocha laterálního kondylu femuru → kraniální interkondylární oblast tibie. Vaz leží uvnitř pouzdra, ale mimo synoviální dutinu; dvě funkční části zde nejsou rozlišeny.'],action:['Restrains cranial displacement and excessive internal rotation of the tibia relative to the femur, and helps limit hyperextension.','Omezuje kraniální posun a nadměrnou vnitřní rotaci tibie vůči femuru a pomáhá bránit hyperextenzi.'],relevance:['Separate ligament stability from muscle strength. After cruciate surgery, the procedure, meniscal findings and surgeon’s restrictions determine progression; a stronger quadriceps does not replace an intact ligament.','Rozlišujte vazivovou stabilitu a svalovou sílu. Po operaci určuje postup typ zákroku, stav menisků a omezení operatéra; silnější kvadriceps nenahrazuje neporušený vaz.'],recall:['Which relative movement does cranial drawer describe? Why does a TPLO not recreate this ligament?','Jaký vzájemný pohyb popisuje kraniální zásuvka? Proč TPLO tento vaz nevytváří znovu?'],lab:'07',bilateral:true},
 {key:'caudal_cruciate',name:['Caudal cruciate ligament','Zkřížený vaz kaudální'],region:'Hindlimb',points:[[-.34158,.30328,-.06248],[-.35681,.29750,-.07109],[-.37204,.29171,-.07970]],attachments:['Lateral surface of the medial femoral condyle → caudal intercondylar region of the tibia. Crosses the cranial cruciate ligament within the joint capsule.','Laterální plocha mediálního kondylu femuru → kaudální interkondylární oblast tibie. Uvnitř kloubního pouzdra kříží kraniální zkřížený vaz.'],action:['Restrains caudal displacement of the tibia relative to the femur and contributes to rotational stability.','Omezuje kaudální posun tibie vůči femuru a podílí se na rotační stabilitě.'],relevance:['Do not infer which cruciate ligament is affected from the direction of lameness. Instability testing and interpretation require a veterinary examination.','Z charakteru kulhání nelze určit postižený zkřížený vaz. Testování a posouzení nestability vyžaduje veterinární vyšetření.'],recall:['Compare the direction of translation restrained by each cruciate ligament.','Porovnejte směry posunu, kterým brání oba zkřížené vazy.'],lab:'07',bilateral:true},
 {key:'stifle_medial_collateral',name:['Stifle medial collateral ligament','Mediální postranní vaz kolena'],region:'Hindlimb',points:[[-.34347,.31426,-.06488],[-.36459,.29326,-.05913],[-.38570,.27226,-.06139]],attachments:['Medial femoral epicondyle → proximal medial tibia. It is closely associated with the medial meniscus.','Mediální epikondyl femuru → proximální mediální tibie. Je těsně spojen s mediálním meniskem.'],action:['Resists valgus opening of the stifle and helps control rotation. Its tension changes with joint position.','Brání valgóznímu rozevírání kolena a pomáhá řídit rotaci. Napětí se mění podle polohy kloubu.'],relevance:['Collateral integrity and meniscal condition matter when interpreting a stifle injury. A painful end range is not an invitation to stretch harder.','Při hodnocení poranění kolena záleží na postranních vazech i meniscích. Bolest v krajní poloze není důvodem k silnějšímu protažení.'],recall:['Which side opens in valgus stress, and which collateral ligament opposes it?','Která strana se otevírá při valgózním zatížení a který vaz tomu brání?'],lab:'07',bilateral:true},
 {key:'stifle_lateral_collateral',name:['Stifle lateral collateral ligament','Laterální postranní vaz kolena'],region:'Hindlimb',points:[[-.34512,.31357,-.09247],[-.36281,.30238,-.09898],[-.38049,.29119,-.09750]],attachments:['Lateral femoral epicondyle → head of the fibula. The popliteus tendon separates it from the lateral meniscus.','Laterální epikondyl femuru → hlava fibuly. Šlacha podkolenního svalu jej odděluje od laterálního menisku.'],action:['Resists varus opening of the stifle and contributes to rotational stability.','Brání varóznímu rozevírání kolena a přispívá k rotační stabilitě.'],relevance:['Distinguish the fibular attachment from the tibial attachment of the medial collateral ligament. Study both in an oblique view.','Rozlište úpon na fibulu od tibiálního úponu mediálního postranního vazu. Oba porovnejte v šikmém pohledu.'],recall:['Why is the lateral meniscus more mobile than the medial one?','Proč je laterální meniskus pohyblivější než mediální?'],lab:'07',bilateral:true},
 {key:'patellar',name:['Patellar ligament','Čéškový vaz'],region:'Hindlimb',points:[[-.33046,.28634,-.07772],[-.34535,.28195,-.07782],[-.36025,.27756,-.07792]],attachments:['Apex of the patella → tibial tuberosity; the distal continuation of the quadriceps extensor apparatus. Dogs have one patellar ligament.','Hrot čéšky → drsnatina tibie; distální pokračování extenzorového aparátu kvadricepsu. Pes má jeden čéškový vaz.'],action:['Transmits quadriceps force through the patella to extend the stifle. A ligament transmits force; it does not actively contract.','Přenáší sílu kvadricepsu přes čéšku k extenzi kolena. Vaz přenáší sílu, ale aktivně se nestahuje.'],relevance:['Trace the whole extensor mechanism when studying patellar luxation. Surgical realignment can involve bone as well as soft tissue, so wound closure alone does not establish readiness for exercise.','Při studiu luxace čéšky sledujte celý extenzorový aparát. Chirurgická korekce může zasáhnout kost i měkké tkáně; uzavřená rána proto sama nepotvrzuje připravenost k zátěži.'],recall:['Follow force from quadriceps to tibia and name every link.','Sledujte přenos síly od kvadricepsu k tibii a pojmenujte všechny články.'],lab:'07',bilateral:true},
 {key:'elbow_medial_collateral',name:['Elbow medial collateral ligament · guide','Mediální postranní vaz lokte · schéma'],region:'Forelimb',points:[[.14992,.27987,-.05038],[.14961,.26575,-.05278],[.14930,.25162,-.06119]],attachments:['Medial humeral epicondyle → proximal radius and ulna through separate portions. This single guide shows only the general course, not both branches.','Mediální epikondyl humeru → proximální radius a ulna prostřednictvím samostatných částí. Jednoduché schéma ukazuje průběh, nikoli obě větve.'],action:['Supports the medial elbow against valgus opening while permitting the normal hinge movement.','Zpevňuje mediální stranu lokte proti valgóznímu rozevírání a dovoluje normální kladkový pohyb.'],relevance:['Identify the epicondyle and distinguish the ligament from adjacent flexor origins before discussing palpation. Ligaments are not reliably isolated by surface palpation alone.','Najděte epikondyl a odlište vaz od okolních začátků flexorů. Samotnou povrchovou palpací nelze vazy spolehlivě izolovat.'],recall:['Name the three bones of the elbow and explain collateral support.','Jmenujte tři kosti lokte a vysvětlete podporu postranních vazů.'],lab:'04',bilateral:true},
 {key:'elbow_lateral_collateral',name:['Elbow lateral collateral ligament · guide','Laterální postranní vaz lokte · schéma'],region:'Forelimb',points:[[.14456,.28132,-.08216],[.14196,.26723,-.08230],[.13936,.25313,-.07644]],attachments:['Lateral humeral epicondyle → proximal radius and ulna through separate portions. Branch detail is omitted in this teaching guide.','Laterální epikondyl humeru → proximální radius a ulna prostřednictvím samostatných částí. Větvení není v tomto schématu zobrazeno.'],action:['Supports the lateral elbow against varus opening and contributes to stability during weight bearing.','Zpevňuje laterální stranu lokte proti varóznímu rozevírání a přispívá ke stabilitě při zatížení.'],relevance:['Compare the ligament with the annular ligament of the radius, which has a different course and is not included in this overlay.','Porovnejte tento vaz s prstencovým vazem radia, který má jiný průběh a není v této vrstvě obsažen.'],recall:['Which collateral ligament opposes varus stress?','Který postranní vaz brání varóznímu zatížení?'],lab:'04',bilateral:true},
 {key:'sacrotuberous',name:['Sacrotuberous ligament','Křížovosedací vaz'],region:'Hindlimb',points:[[-.26734,.50345,-.02086],[-.32440,.47839,-.03002],[-.38146,.45332,-.03917]],attachments:['Lateral sacral/first caudal region → ischial tuberosity. This dog ligament is absent in the cat.','Laterální oblast křížové kosti a prvního ocasního obratle → sedací hrbol. Tento psí vaz u kočky chybí.'],action:['Provides a fibrous link between the caudal axial skeleton and the ischium, contributing to the boundary of the pelvic outlet.','Vytváří vazivové spojení kaudální osové kostry se sedací kostí a podílí se na ohraničení pánevního východu.'],relevance:['A useful species comparison for the exam. Do not interpret regional tenderness as a specific ligament diagnosis without an examination.','Užitečný mezidruhový rozdíl ke zkoušce. Citlivost v této oblasti bez vyšetření neznamená konkrétní diagnózu vazu.'],recall:['Does a cat have this ligament? Locate the ischial tuberosity.','Má kočka tento vaz? Ukažte sedací hrbol.'],lab:'07',bilateral:true},
 {key:'nuchal',name:['Nuchal ligament · funicular guide','Šíjový vaz · schéma provazcovité části'],region:'Neck & trunk',points:[[.22568,.67598,0],[.17901,.61482,0],[.13234,.54967,0]],attachments:['Spinous process of the axis (C2) → cranial thoracic spinous region (T1), continuing into the supraspinous ligament. In the dog it does not attach to the skull; the lamellar part is absent.','Trnový výběžek čepovce (C2) → kraniální hrudní trnová oblast (T1), s pokračováním do nadtrnového vazu. U psa se neupíná na lebku a lamelární část chybí.'],action:['An elastic passive support for the neck that limits ventral bending and reduces the muscular effort needed for support.','Pružná pasivní opora krku, která omezuje ventrální ohnutí a snižuje nároky na svalovou podporu.'],relevance:['The cat lacks a nuchal ligament. This added guide is separate from the source mesh called m_Ligament, whose identity remains qualified.','Kočka šíjový vaz nemá. Přidané schéma je odděleno od původního objektu m_Ligament, jehož identita zůstává nejistá.'],recall:['Why would drawing this canine ligament to the skull be misleading?','Proč by zakreslení tohoto psího vazu až k lebce bylo zavádějící?'],lab:'09',bilateral:false}
];
export const ligamentCount=guides.reduce((n,g)=>n+(g.bilateral?2:1),0);
export function addLigaments(atlas:Atlas):Atlas{
 const parts:Part[]=guides.flatMap(g=>(g.bilateral?[-1,1]:[0]).map(side=>{
  const path=g.points.map(p=>[p[0],p[1],side===0?0:Math.abs(p[2])*side]);
  const radius=g.key==='patellar'?.0027:.0018;
  const bounds=[0,1].map(end=>[0,1,2].map(axis=>(end?Math.max(...path.map(p=>p[axis])):Math.min(...path.map(p=>p[axis])))+(end?radius:-radius)));
  return {id:`guide_${g.key}${side<0?'_L':side>0?'_R':''}`,system:'ligament' as const,vertexOffset:0,vertexCount:0,indexOffset:0,indexCount:0,path,radius,anatomicalRegion:g.region,center:bounds[0].map((v,i)=>(v+bounds[1][i])/2),bounds};
 }));
 return {...atlas,parts:[...atlas.parts,...parts]};
}
export function ligamentDetail(part:Part,language:Language){
 const g=guides.find(g=>part.id===`guide_${g.key}`||part.id===`guide_${g.key}_L`||part.id===`guide_${g.key}_R`);if(!g)return;
 const i=language==='cs'?1:0;
 return {title:g.name[i],profile:g.key,side:part.id.endsWith('_L')?['Left','Vlevo'][i]:part.id.endsWith('_R')?['Right','Vpravo'][i]:['Midline','Střední čára'][i],overview:['A selectable schematic ligament guide added for joint anatomy revision. Use the bones to orient yourself, then trace its attachments and resisting action.','Volitelné schéma vazu přidané pro opakování kloubní anatomie. Orientujte se podle kostí, potom sledujte úpony a pohyb, kterému vaz brání.'][i],location:g.attachments[i],attachments:g.attachments[i],function:g.action[i],nerve:['Ligaments have sensory innervation, including nociceptive and mechanosensory endings; they have no muscle-like motor action. A named nerve distribution is not mapped by this guide.','Vazy mají senzitivní inervaci včetně nociceptivních a mechanosenzitivních zakončení; nemají svalovou motorickou funkci. Konkrétní nervové větve toto schéma nezobrazuje.'][i],physio:g.relevance[i],recall:g.recall[i],warning:['SCHEMATIC ADDITION: approximate course and attachment regions; thickness is enlarged for visibility. Not segmented from the source model or independently anatomically validated.','SCHEMATICKÝ DOPLNĚK: přibližný průběh a oblasti úponů; tloušťka je zvětšena pro viditelnost. Nejde o segmentaci původního modelu ani nezávisle anatomicky ověřenou geometrii.'][i],modelNote:['These guides show selected ligaments, not a complete ligament atlas. Hide muscles or use the Bones + ligaments preset. Isolation shows the guide without its bony context.','Schémata zobrazují vybrané vazy, nikoli úplný atlas vazů. Skryjte svaly nebo použijte předvolbu Kosti a vazy. Izolace zobrazí vaz bez kostního kontextu.'][i],sources:[g.lab],references:[{title:['University of Minnesota · comparative anatomy','University of Minnesota · srovnávací anatomie'][i],url:`https://vanat.ahc.umn.edu/carnLabs/Lab${g.lab}/Lab${g.lab}.html`}]};
}
