'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Bone,Layers3,Search,RotateCcw,RotateCw,Focus,EyeOff,ArrowUpRight,BookOpen,ChevronRight,X,Dog,Check,Info,PanelLeftClose} from 'lucide-react';
import {Button} from '@/components/ui/button';
import AnatomyScene from './scene';
import {detailFor,noteCoverage} from './study-notes';
import {type Atlas,type SceneState,type System,initial,systems,displayName,region,notes,isShown} from './anatomy';
export default function Home(){
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState<SceneState>(initial),[query,setQuery]=useState(''),[area,setArea]=useState('All regions'),[error,setError]=useState(''),[tab,setTab]=useState<'explore'|'study'>('explore'),[about,setAbout]=useState(false),[mobile,setMobile]=useState(false),[revealed,setRevealed]=useState(false),[card,setCard]=useState(0);
 const search=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),inspector=useRef<HTMLElement>(null);
 useEffect(()=>{inspector.current?.scrollTo({top:0});},[state.selected,tab]);
 useEffect(()=>{const abort=new AbortController();fetch('/models/catalog.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort();},[]);
 useEffect(()=>{if(about)dialog.current?.showModal();else dialog.current?.close();},[about]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setMobile(true);search.current?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const selected=atlas?.parts.find(p=>p.id===state.selected),note=selected?detailFor(selected):undefined;
 const results=useMemo(()=>atlas?.parts.filter(p=>(area==='All regions'||region(p)===area)&&(!query||`${displayName(p.id)} ${p.id} ${p.system}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>displayName(a.id).localeCompare(displayName(b.id)))||[],[atlas,query,area]);
 const count=atlas?.parts.filter(p=>isShown(p,state)).length||0;
 const choose=(id:string)=>{setState(s=>({...s,selected:id,isolate:false,hidden:s.hidden.filter(h=>h!==id),rotate:false}));setMobile(false)};
 const reset=()=>{setState(s=>({...initial,reset:s.reset+1}));setQuery('');setArea('All regions')};
 const toggle=(system:System)=>setState(s=>({...s,selected:null,isolate:false,systems:s.systems.includes(system)?s.systems.filter(x=>x!==system):[...s.systems,system]}));
 const quiz=notes[card%notes.length];
 return <main className="atlas-app">
  <header className="app-header"><div className="brand"><span className="brand-mark"><Dog size={25}/></span><div><h1>Canine Atlas<span>3D</span></h1><p>ANATOMY FOR MOVEMENT</p></div></div><nav aria-label="Study modes" className="mode-tabs"><button className={tab==='explore'?'active':''} onClick={()=>setTab('explore')}><Layers3 size={16}/>Explore</button><button className={tab==='study'?'active':''} onClick={()=>setTab('study')}><BookOpen size={16}/>Study</button></nav><button className="source-button" onClick={()=>setAbout(true)}><Info size={17}/><span>Sources & scope</span></button></header>
  <div className="workspace">
   <aside className={`sidebar ${mobile?'mobile-open':''}`} aria-label="Anatomy controls"><div className="side-heading"><span>ANATOMICAL STRUCTURES</span><button className="mobile-close icon" onClick={()=>setMobile(false)} aria-label="Close structure controls"><X size={18}/></button></div>
    <label className="search-field"><Search size={17}/><input ref={search} placeholder="Find a structure…" aria-label="Find a structure" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></label>
    <div className="section-title"><h2>Layers</h2><span>{systems.length}</span></div>
    <div className="presets"><button onClick={()=>setState(s=>({...s,systems:['bone','muscle'],selected:null,isolate:false,hidden:[]}))}>Musculoskeletal</button><button onClick={()=>setState(s=>({...s,systems:['bone'],selected:null,isolate:false,hidden:[]}))}>Skeleton</button></div>
    <div className="layer-list">{systems.map(sys=><button key={sys.id} className="layer-row" aria-pressed={state.systems.includes(sys.id)} onClick={()=>toggle(sys.id)}><span className="layer-dot" style={{background:sys.color}}/><span>{sys.name}</span><small>{atlas?.parts.filter(p=>p.system===sys.id).length??'—'}</small><span className={`switch ${state.systems.includes(sys.id)?'on':''}`}><i/></span></button>)}</div>
    <label className="opacity-label">Muscle opacity <output>{Math.round(state.opacity*100)}%</output><input aria-label="Muscle opacity" type="range" min="0.1" max="1" step="0.05" value={state.opacity} onChange={e=>setState(s=>({...s,opacity:+e.target.value}))}/></label>
    <div className="section-title"><h2>Browse anatomy</h2><span>{results.length}</span></div>
    <select aria-label="Filter by anatomical region" value={area} onChange={e=>setArea(e.target.value)}>{['All regions','Forelimb','Hindlimb','Neck & trunk','Head'].map(r=><option key={r}>{r}</option>)}</select>
    <div className="structure-list">{results.map(p=><button key={p.id} className={`structure-row ${state.selected===p.id?'selected':''}`} onClick={()=>choose(p.id)}><span className="tiny-dot" style={{background:systems.find(s=>s.id===p.system)?.color}}/><span>{displayName(p.id)}</span><ChevronRight size={13}/></button>)}{!results.length&&<p className="empty">{atlas?'No matching structures. Try a muscle name or choose all regions.':'Loading structures…'}</p>}</div>
    <div className="side-foot"><span className="live-dot"/>{noteCoverage.pieces} pieces · {noteCoverage.pieces} study notes</div>
   </aside>
   <section className="viewer" aria-label="Canine anatomy explorer">
    <div className="viewer-top"><div><span className="eyebrow">MUSCULOSKELETAL ATLAS</span><h2>{state.isolate&&selected?'Isolated structure':state.explode>0?'Exploded anatomy':'Canis lupus familiaris'}</h2><p>{count} visible pieces <span>·</span> {state.isolate?'Select another structure to return':'Select a structure to explore'}</p></div><button className="mobile-controls" onClick={()=>setMobile(true)}><Layers3 size={17}/>Layers & search</button></div>
    {atlas&&<AnatomyScene atlas={atlas} state={state} onSelect={choose}/>}
    {error&&<div role="alert" className="load-card"><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></div>}
    {atlas&&count===0&&<div className="load-card"><strong>No structures visible</strong><p>Turn on a layer or restore the anatomy.</p><button onClick={reset}>Restore anatomy</button></div>}
    <div className="orientation"><span>CAMERA PRESET</span><small>{state.view==='lateral'?'Left lateral':state.view==='right'?'Right lateral':state.view==='dorsal'?'Dorsal':state.view==='cranial'?'Cranial':'Oblique'} view</small></div>
    <nav className="view-tools" aria-label="Camera controls">{[['lateral','L','Left lateral view'],['right','R','Right lateral view'],['cranial','Cr','Cranial view'],['dorsal','D','Dorsal view'],['three-quarter','¾','Oblique view']].map(([v,label,title])=><button key={v} title={title} aria-label={title} aria-pressed={state.view===v} onClick={()=>setState(s=>({...s,view:v,explode:0,reset:s.reset+1,rotate:false}))}>{label}</button>)}<i/><button title="Auto rotate" aria-label="Auto rotate" aria-pressed={state.rotate} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}><RotateCw size={17}/></button><button title="Reset view and layers" aria-label="Reset view and layers" onClick={reset}><RotateCcw size={17}/></button></nav>
    <div className="explode-dock"><Layers3 size={20}/><div><label htmlFor="explode">Explode anatomy <output>{Math.round(state.explode*100)}%</output></label><input id="explode" type="range" min="0" max="1" step="0.01" value={state.explode} onChange={e=>setState(s=>({...s,explode:+e.target.value,rotate:false,isolate:false}))}/><div className="range-captions"><span>Assembled</span><span>Separate pieces</span></div></div><button aria-label="Reassemble anatomy" onClick={()=>setState(s=>({...s,explode:0,reset:s.reset+1}))}><RotateCcw size={17}/></button></div>
    <footer className="viewer-footer"><span>Drag to orbit <b>·</b> Scroll / pinch to zoom <b>·</b> Click to inspect</span><span>Educational reference</span></footer>
   </section>
   <aside ref={inspector} className="inspector" aria-label={tab==='study'?'Study cards':'Structure details'}>
    {tab==='study'?<><div className="eyebrow mint">ACTIVE RECALL</div><h2>Movement cards</h2><p className="muted">Recall the action, then check your answer.</p><div className="quiz-progress"><span>Card {card%notes.length+1} of {notes.length}</span><BookOpen size={17}/></div><article className="quiz-card"><span>WHAT DOES IT DO?</span><h3>{quiz.title}</h3>{revealed?<><p>{quiz.action}</p><div className="rule"/><p className="muted">{quiz.landmark}</p><a href={`https://vanat.ahc.umn.edu/carnLabs/Lab${quiz.lab}/Lab${quiz.lab}.html`} target="_blank" rel="noreferrer">Review anatomy source <ArrowUpRight size={14}/></a></>:<p className="muted">Name the joint action and trace the attachments.</p>}</article><Button className="primary" onClick={()=>{if(revealed){setCard(c=>c+1);setRevealed(false)}else setRevealed(true)}}>{revealed?'Next card':'Reveal answer'}<ChevronRight size={17}/></Button><button className="text-button" onClick={()=>{const p=atlas?.parts.find(p=>quiz.match.test(p.id));if(p){choose(p.id);setTab('explore');setState(s=>({...s,selected:p.id,isolate:true,explode:0,reset:s.reset+1}))}}}>Find in the 3D model <Focus size={15}/></button></>:selected?<>
     <div className="eyebrow mint">{systems.find(s=>s.id===selected.system)?.name} <span> / </span> {region(selected)}</div><div className="detail-title"><h2>{note?.title??displayName(selected.id)}</h2><button className="icon" aria-label="Clear selection" onClick={()=>setState(s=>({...s,selected:null,isolate:false}))}><X size={18}/></button></div>
     <div className="selected-pill"><span/>Selected in 3D</div>
     {note&&<div className="full-note">
      <div className="note-meta"><span>{note.side}</span><span>Detailed study note</span></div>
      {note.warning&&<div className="identity-warning" role="note"><strong>Source identity qualification</strong><p>{note.warning}</p></div>}
      <p className="note-overview">{note.overview}</p>
      <section><h3>Location & relationships</h3><p>{note.location}</p></section>
      <section><h3>Attachments & articulations</h3><p>{note.attachments}</p></section>
      <section><h3>Function & biomechanics</h3><p>{note.function}</p></section>
      <section><h3>Nerve supply</h3><p>{note.nerve}</p></section>
      <section><h3>Physiotherapy relevance</h3><p>{note.physio}</p></section>
      <div className="study-note"><BookOpen size={18}/><div><strong>Recall prompt</strong><p>{note.recall}</p></div></div>
      {note.modelNote&&<section className="model-interpretation"><h3>About this model piece</h3><p>{note.modelNote}</p></section>}
      <section className="note-references"><h3>References & further study</h3>{note.references.map(ref=><a className="reference-link" key={ref.url} href={ref.url} target="_blank" rel="noreferrer">{ref.title}<ArrowUpRight size={14}/></a>)}</section>
     </div>}
     <div className="source-id"><span>ORIGINAL MODEL NAME</span><code>{selected.id}</code><small>Source labels are retained; some are abbreviated or group multiple structures.</small></div>
     <Button className="primary" onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0,reset:s.reset+1}))}><Focus size={17}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}</Button><button className="text-button" onClick={()=>setState(s=>({...s,hidden:[...s.hidden,selected.id],selected:null,isolate:false}))}><EyeOff size={16}/>Hide this piece</button>
    </>:<><div className="eyebrow mint">EXPLORE & UNDERSTAND</div><h2>Anatomy in motion starts here.</h2><p className="muted">Every piece has study notes covering its location, connections, function and physiotherapy relevance. Select a structure to begin.</p><div className="intro-icon"><Bone size={34}/></div><h3>Start with a region</h3>{['Forelimb','Hindlimb','Neck & trunk'].map((r,i)=><button className="region-card" key={r} onClick={()=>{setArea(r);setQuery('');setMobile(true);search.current?.focus()}}><span className="region-number">0{i+1}</span><span>{r}<small>{i===0?'Shoulder · elbow · carpus':i===1?'Hip · stifle · tarsus':'Vertebrae · axial muscles'}</small></span><ChevronRight size={16}/></button>)}<div className="study-note"><BookOpen size={18}/><div><strong>Build your recall</strong><p>Practice muscle actions with {notes.length} movement cards.</p><button onClick={()=>setTab('study')}>Open study cards <ChevronRight size={14}/></button></div></div></>}
    {state.hidden.length>0&&<button className="restore-button" onClick={()=>setState(s=>({...s,hidden:[]}))}>Restore {state.hidden.length} hidden {state.hidden.length===1?'piece':'pieces'}</button>}
    <p className="scope-note">Research model, not a clinical assessment tool. Notes describe anatomy and study relevance, not treatment instructions. Confirm model interpretations alongside your veterinary course materials.</p>
   </aside>
  </div>
  <dialog ref={dialog} className="about-dialog" onCancel={()=>setAbout(false)} onClick={e=>{if(e.target===dialog.current)setAbout(false)}}><button className="dialog-close icon" aria-label="Close sources" onClick={()=>setAbout(false)}><X size={22}/></button><span className="eyebrow mint">SOURCES & SCOPE</span><h2>A canine atlas for study.</h2><p>This explorer adapts the interaction patterns of Human Atlas: 3D selection, layer controls, search, isolation and exploded views.</p><h3>Canine geometry</h3><p>MusculoskeletalDog by Vittorio La Barbera (2025), released under MIT. The associated research describes Pharaoh dog geometry originating from leo3Dmodels and dm_control. It is a research-used anatomical model, not a CT reconstruction or a veterinarian-validated teaching atlas.</p><p>{atlas?.parts.length??425} selectable pieces. Pieces include grouped bones, separate muscle portions, connective tissue and surface features; these counts are not anatomical totals. Organs and nerves are not included.</p><p>Converted from STL and SKN to indexed geometry in the source reference pose. Colors, labels and the exploded layout are adapted for this viewer; no simulated joint movement or treatment guidance is provided.</p><a href="https://github.com/vittorione94/MusculoskeletalDog" target="_blank" rel="noreferrer">Model repository <ArrowUpRight size={15}/></a><a href="https://arxiv.org/html/2506.23768v2" target="_blank" rel="noreferrer">Research & model provenance <ArrowUpRight size={15}/></a><a href="/models/LICENSE-MODEL.txt" target="_blank">Model licence <ArrowUpRight size={15}/></a><h3>Study content</h3><p>All 425 selectable pieces have detailed study notes, organized into 168 anatomical profiles. Bilateral and repeated pieces share the relevant anatomy, with side and model-specific context. Notes cover location, attachments or articulations, function, nerve supply, physiotherapy relevance and a recall question. 43 pieces carry explicit qualifications where names, species conventions or segmentation are uncertain. References include university veterinary anatomy teaching material and model provenance. Use the canine examples alongside your prescribed text; source images and dissection instructions are not reproduced. Notes have not undergone independent veterinary peer review.</p><a href="https://vanat.ahc.umn.edu/carnLabs/" target="_blank" rel="noreferrer">University of Minnesota · Carnivore anatomy <ArrowUpRight size={15}/></a><a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">Human Atlas · interface reference (MIT) <ArrowUpRight size={15}/></a></dialog>
 </main>
}

