'use client';
import {useRef,useState} from 'react';
import {BookOpen,ChevronRight,Dog} from 'lucide-react';
import {practiceStations} from './practical-data';
import {examModules,examUrl,local} from './exam-data';
import {type Language} from './i18n';
import {sitePath} from './site-path';
import {useChecklist} from './study-checklist';
import StudyVisuals from './study-visuals';
const checkIds=practiceStations.flatMap(s=>s.checks.map((_,i)=>`${s.id}.${i}`));
export default function PracticalStudy({language,onLesson}:{language:Language;onLesson:(topic:string,criterion:string)=>void}){
 const e=(en:string,cs:string)=>language==='cs'?cs:en;
 const [active,setActive]=useState(practiceStations[0].id),[filter,setFilter]=useState('all');
 const {checked,ready,error,toggle}=useChecklist('canine-atlas-practice-rehearsal-v1',checkIds);
 const heading=useRef<HTMLHeadingElement>(null);
 const visible=practiceStations.filter(s=>filter==='all'||s.kind===filter);
 const station=visible.find(s=>s.id===active)||visible[0];
 const kind=(value:string)=>value==='home'?e('Home observation','Domácí pozorování'):value==='desk'?e('Rehearse without a dog','Nácvik bez psa'):e('With an instructor','S instruktorem');
 const choose=(id:string)=>{setActive(id);requestAnimationFrame(()=>{heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'start'});});};
 return <section className="practical-page" aria-label={e('Practical exam preparation','Příprava na praktickou zkoušku')}>
  <header className="practical-hero"><div><span className="eyebrow mint">{e('PRACTISE · OBSERVE · EXPLAIN','NACVIČIT · POZOROVAT · VYSVĚTLIT')}</span><h1>{e('Prepare with your dog','Příprava s vaším psem')}</h1><p>{e('12 rehearsal stations. Build calm handling, precise observation and clear explanations before supervised clinical practice.','12 cvičných stanovišť. Rozvíjejte klidný přístup, přesné pozorování a srozumitelné vysvětlení před klinickou praxí pod dohledem.')}</p></div><Dog size={54} aria-hidden="true"/></header>
  <div className="practice-intro"><p><strong>{e('Start with your dog’s current limits.','Začněte aktuálními možnostmi psa.')}</strong> {e('These are generic study rehearsals, not an individual rehabilitation prescription. If your dog has pain, lameness, illness, recent surgery or exercise restrictions, use the video/model alternatives and ask its veterinarian which activities are suitable. Never force participation.','Jde o obecný studijní nácvik, nikoli individuální rehabilitační předpis. Při bolesti, kulhání, nemoci, nedávné operaci či omezení zátěže použijte video nebo model a vhodnost aktivity ověřte u veterináře. Účast nevynucujte.')}</p><p>{e('Choose one suitable station. Prepare → observe → pause → explain → record. Stop at withdrawal, pain or fatigue; new breathing difficulty or collapse needs urgent veterinary help. No fixed exercise dose is prescribed here.','Vyberte jedno vhodné stanoviště. Připravit → pozorovat → pauza → vysvětlit → zapsat. Při odchodu, bolesti či únavě skončete; nová dušnost či kolaps potřebuje naléhavou veterinární pomoc. Pevná dávka cvičení zde není předepsána.')}</p></div>
  <div className="practice-layout"><aside className="practice-nav">
   <label htmlFor="practice-filter">{e('Choose your setting','Zvolte prostředí')}</label><select id="practice-filter" value={filter} onChange={ev=>setFilter(ev.target.value)}><option value="all">{e('All stations','Všechna stanoviště')}</option>{['home','desk','supervised'].map(k=><option value={k} key={k}>{kind(k)}</option>)}</select>
   <nav aria-label={e('Practice stations','Cvičná stanoviště')}>{visible.map(s=><button key={s.id} aria-current={station.id===s.id?'page':undefined} onClick={()=>choose(s.id)}><span className="practice-number">{String(practiceStations.indexOf(s)+1).padStart(2,'0')}</span><span>{local(s.title,language)}<small>{kind(s.kind)}</small></span><ChevronRight size={15}/></button>)}</nav>
   <p className="practice-saved" aria-live="polite">{e(`${checked.length} / ${checkIds.length} rehearsal checks recorded`,`${checked.length} / ${checkIds.length} bodů nácviku zaznamenáno`)}</p>
   <small>{e('Self-recorded in this browser. These ticks do not certify practical competence.','Vlastní záznam v tomto prohlížeči. Označení nepotvrzuje praktickou způsobilost.')}</small>
  </aside>
  <article className="practice-station" key={station.id}>
   <span className={`practice-kind ${station.kind}`}>{kind(station.kind)}</span><h2 ref={heading} tabIndex={-1}>{local(station.title,language)}</h2><p className="practice-goal">{local(station.goal,language)}</p>
   {station.image&&<figure className="practice-image"><img src={sitePath(`/study/practice/${station.image}.webp`)} alt={local(station.alt!,language)} width={1536} height={1024} loading="lazy"/><figcaption>{e('AI-generated illustration of the setting. Not an anatomical reference or a demonstration of a clinical technique; follow the written station instructions.','Ilustrace prostředí vytvořená AI. Není anatomickým podkladem ani předvedením klinické techniky; postupujte podle písemného zadání stanoviště.')}</figcaption></figure>}
   {station.visual&&<StudyVisuals topic={station.visual} language={language}/>}
   <h3>{e('Set up','Příprava')}</h3><p>{local(station.setup,language)}</p>
   <h3>{e('Rehearsal steps','Postup nácviku')}</h3><ol className="practice-steps">{station.steps.map((step,i)=><li key={i}>{local(step,language)}</li>)}</ol>
   <div className="practice-observe"><h3>{e('What to notice','Čeho si všímat')}</h3><p>{local(station.observe,language)}</p></div>
   <div className="practice-stop"><h3>{e('Stop / change the plan','Ukončit / změnit plán')}</h3><p>{local(station.stop,language)}</p></div>
   <div className="practice-oral"><span className="eyebrow mint">{e('SAY IT ALOUD','ŘEKNĚTE NAHLAS')}</span><p>{local(station.oral,language)}</p></div>
   <section className="learning-checklist"><h3>{e('Record your rehearsal','Záznam nácviku')}</h3><p>{station.kind==='supervised'?e('These checks record preparation for teaching, not completion of a clinical skill. Ask your instructor to assess your live-animal technique.','Body zaznamenávají přípravu do výuky, nikoli zvládnutí klinické dovednosti. Provedení na zvířeti nechte posoudit instruktorem.'):e('Tick only what you actually rehearsed. Untick it whenever you want to revisit it.','Označte jen skutečně nacvičené body. Označení zrušte, kdykoli se chcete vrátit.')} </p>{station.checks.map((check,i)=>{const id=`${station.id}.${i}`;return <label key={id}><input type="checkbox" disabled={!ready} checked={checked.includes(id)} onChange={()=>toggle(id)}/><span>{local(check,language)}</span></label>;})}{error&&<p role="status">{e('Progress could not be read or saved. It may only last for this visit.','Postup nelze načíst či uložit. Může platit jen při této návštěvě.')}</p>}</section>
   <section className="practice-connections"><h3>{e('Connect to exam lessons','Propojit s tématy zkoušky')}</h3><div>{station.criteria.map(id=>{const [topic,criterion]=id.split('.'),m=examModules.find(m=>m.id===topic)!;return <button key={id} onClick={()=>onLesson(topic,criterion)}><BookOpen size={14}/>{local(m.title,language)} · {criterion.toUpperCase()}<ChevronRight size={14}/></button>;})}</div>
   <a className="practice-book" href={sitePath(`/?book=${station.book.id}&page=${station.book.page}`)} target="_blank" rel="noreferrer">{e('Read in your book','Přečíst v knize')}: {local(station.book.label,language)} · {e('PDF page','strana PDF')} {station.book.page} ↗</a><small>{e('PDF numbering, not printed page numbers. Opens in a new tab.','Číslování PDF, nikoli tištěných stran. Otevře se v nové kartě.')}</small></section>
  </article></div>
  <footer className="practice-sources"><h2>{e('Complete your preparation','Dokončete přípravu')}</h2><p>{e('Use the 58-criterion lesson checklist, quizzes and book chapters alongside these stations. Practise orthopedic and neurological examination, manual techniques, assistance and continence care with a qualified instructor. The qualification includes cats as well as dogs. These notes and images have not had independent veterinary peer review and cannot guarantee an exam pass.','Vedle stanovišť používejte seznam 58 kritérií, testy a kapitoly knih. Ortopedické a neurologické vyšetření, manuální techniky, asistenci a péči o kontinenci nacvičujte s kvalifikovaným instruktorem. Kvalifikace zahrnuje kočky i psy. Poznámky a obrázky nemají nezávislou veterinární odbornou recenzi a nemohou zaručit složení zkoušky.')}</p><a href={examUrl} target="_blank" rel="noreferrer">{e('NSK assessment standard','Hodnoticí standard NSK')} ↗</a><a href="https://riney.vet.cornell.edu/member-benefits-health-tips/grooming-cooperative-care-february-2026?hs_amp=true" target="_blank" rel="noreferrer">{e('Cornell · cooperative care','Cornell · spolupráce při péči')} ↗</a><a href="https://www.aaha.org/resources/2022-aaha-pain-management-guidelines-for-dogs-and-cats/nonpharmacologic-modalities-for-pain-management/" target="_blank" rel="noreferrer">{e('AAHA · rehabilitation and pain care','AAHA · rehabilitace a péče o bolest')} ↗</a></footer>
 </section>;
}
