import {examModules,type Bilingual} from './exam-data';
import {photoData} from './study-visuals';
export type Question={id:string;topic:string;criterion:string;prompt:Bilingual;choices:{id:string;text:Bilingual}[];correctId:string;explanation:Bilingual;photo?:{kind:keyof typeof photoData;mark:number}};
// One original question per mapped criterion. First authored choice is correct;
// presentation order is shuffled per run, and answer identity never depends on language.
const rows=`
anatomy|a|Which structure usually links bones and passively constrains joint motion?|Která struktura obvykle spojuje kosti a pasivně omezuje kloubní pohyb?|Ligament|Vaz|Muscle belly|Svalové bříško|Motor nerve|Motorický nerv
anatomy|b|How is the canine thoracic limb attached to the trunk?|Jak je hrudní končetina psa připojena k trupu?|Through a muscular attachment|Prostřednictvím svalového spojení|Through a scapula–rib synovial joint|Synoviálním kloubem lopatky a žebra|Through fusion of scapula and vertebrae|Srůstem lopatky s obratli
anatomy|c|Which structure primarily restrains cranial tibial translation relative to the femur?|Která struktura především omezuje kraniální posun tibie vůči femuru?|Cranial cruciate ligament|Kraniální zkřížený vaz|Patellar ligament|Čéškový vaz|Quadriceps tendon|Šlacha kvadricepsu
anatomy|d|Where does the canine nuchal ligament attach cranially?|Kam se kraniálně upíná šíjový vaz psa?|Axis, C2|Čepovec, C2|Occipital bone of the skull|Týlní kost lebky|Mandible|Dolní čelist
physiology|a|Which structures form the central nervous system?|Které struktury tvoří centrální nervovou soustavu?|Brain and spinal cord|Mozek a mícha|Peripheral nerves and muscles|Periferní nervy a svaly|Tendons and sensory receptors|Šlachy a senzitivní receptory
physiology|b|Which system supplies information about body position?|Který systém poskytuje informace o poloze těla?|Proprioception|Propriocepce|Hemostasis|Hemostáza|Thermoregulation|Termoregulace
physiology|c|Which ion enables the interaction of actin and myosin during muscle activation?|Který iont umožňuje interakci aktinu a myozinu při aktivaci svalu?|Calcium|Vápník|Iron|Železo|Iodide|Jodid
physiology|d|What is the most interpretable way to progress an exercise initially?|Jaký počáteční postup nejlépe umožní vyhodnotit reakci na progresi cviku?|Change one demand and evaluate recovery|Změnit jeden nárok a vyhodnotit zotavení|Increase all demands together|Zvýšit všechny nároky současně|Judge only the number of repetitions|Hodnotit pouze počet opakování
physiology|e|What determines the moment of a force about a joint?|Co určuje moment síly kolem kloubu?|Force and its perpendicular moment arm|Síla a její kolmé rameno|Force and coat thickness|Síla a tloušťka srsti|Body weight alone|Pouze tělesná hmotnost
healing|a|Which phase mainly reorganizes repair tissue?|Která fáze především přestavuje reparační tkáň?|Remodeling|Remodelace|Hemostasis|Hemostáza|Initial inflammation|Počáteční zánět
healing|b|A surgical skin incision has closed. What does that establish?|Operační kožní rána se uzavřela. Co tím lze doložit?|Skin closure, not full strength of deeper repairs|Uzavření kůže, nikoli plnou pevnost hlubších reparací|Complete ligament recovery|Úplné zotavení vazů|Complete osteotomy healing|Úplné zhojení osteotomie
healing|c|What influences peripheral nerve recovery?|Co ovlivňuje zotavení periferního nervu?|Lesion type, continuity and distance to the target|Typ léze, kontinuita a vzdálenost k cíli|Only the patient's body weight|Pouze tělesná hmotnost pacienta|Only the date symptoms started|Pouze datum začátku příznaků
healing|d|Which approach best supports repeatable pain assessment?|Který postup nejlépe podporuje opakovatelné hodnocení bolesti?|A suitable validated scale with repeated observations|Vhodná validovaná škála a opakovaná pozorování|A single heart-rate reading|Jednorázové změření tepu|Coat condition alone|Samotný stav srsti
healing|e|New swelling and worse lameness appear after exercise. What is the next priority?|Po cvičení se objeví nový otok a horší kulhání. Co má nyní přednost?|Reassessment of tolerance and the plan|Přehodnocení tolerance a plánu|Progression based only on the calendar|Progrese pouze podle kalendáře|Recording the repetitions as a success|Zapsání opakování jako úspěchu
healing|f|Why may a previous workload be excessive after immobilization?|Proč může být původní zátěž po imobilizaci nadměrná?|Current muscle capacity and coordination may be reduced|Aktuální svalová kapacita a koordinace mohou být sníženy|Immobilization always increases endurance|Imobilizace vždy zvyšuje vytrvalost|Previous capacity never changes|Původní kapacita se nikdy nemění
assessment|a|Which history question most directly identifies a functional limitation?|Která anamnestická otázka nejpříměji zjistí funkční omezení?|What usual activity can the animal no longer perform?|Kterou běžnou aktivitu zvíře již nezvládá?|What color is the animal's harness?|Jakou barvu má postroj zvířete?|What is the clinic's busiest day?|Který den má klinika nejvíce práce?
assessment|b|What should happen before touching the patient during assessment?|Co má při hodnocení předcházet dotyku pacienta?|Observe behavior, breathing and spontaneous movement|Pozorovat chování, dýchání a spontánní pohyb|Choose the final rehabilitation dose|Zvolit konečnou dávku rehabilitace|Assign a diagnosis from breed alone|Určit diagnózu jen podle plemene
assessment|c|Does the most obvious asymmetry always identify the primary orthopedic problem?|Určuje nejvýraznější asymetrie vždy primární ortopedický problém?|No; compensations may occur elsewhere|Ne; kompenzace se mohou projevit jinde|Yes; compensation cannot affect posture|Ano; kompenzace nemůže ovlivnit postoj|Yes; other examination findings are irrelevant|Ano; ostatní nálezy nejsou podstatné
assessment|d|Does an intact withdrawal reflex prove conscious pain perception?|Dokazuje zachovaný odtahový reflex vědomé vnímání bolesti?|No; a spinal reflex and conscious perception differ|Ne; míšní reflex a vědomé vnímání se liší|Yes; they are the same response|Ano; jde o stejnou odpověď|Yes; withdrawal bypasses the spinal cord|Ano; odtah obchází míchu
assessment|e|What must be standardized when comparing limb circumference over time?|Co je nutné standardizovat při porovnání obvodu končetiny v čase?|Landmarks and measurement position|Orientační body a polohu při měření|The color of the measuring tape|Barvu měřicí pásky|The owner's clothing|Oblečení majitele
assessment|f|Which comparison makes gait videos more interpretable?|Jaké porovnání zlepšuje interpretaci videí chůze?|Comparable pace, surface and viewing angles|Srovnatelná rychlost, povrch a úhly pohledu|Different speeds in every recording|Různé rychlosti v každém záznamu|Only one still image from each recording|Pouze jeden statický obrázek z každého záznamu
orthopedics|a|How should imaging inform rehabilitation planning?|Jak má zobrazovací vyšetření ovlivnit plánování rehabilitace?|Together with the medical report and examination|Společně s lékařskou zprávou a vyšetřením|By itself, without the clinical history|Samostatně, bez anamnézy|Only through the image file name|Pouze prostřednictvím názvu souboru snímku
orthopedics|b|Which statement fits canine cranial cruciate disease?|Které tvrzení odpovídá onemocnění kraniálního zkříženého vazu psa?|It commonly has a degenerative component|Často má degenerativní složku|It always follows one major trauma|Vždy následuje po jednom velkém úrazu|It affects only the thoracic limb|Postihuje pouze hrudní končetinu
orthopedics|c|What is the best starting point for choosing an intervention?|Co je nejlepším východiskem pro volbu intervence?|A functional problem and a permitted goal|Funkční problém a povolený cíl|The newest available device|Nejnovější dostupný přístroj|The exercise with the most repetitions|Cvik s nejvyšším počtem opakování
orthopedics|d|Which information should guide postoperative progression?|Jaké informace mají řídit pooperační progresi?|Procedure, restrictions, tissue status and function|Zákrok, omezení, stav tkání a funkce|The week number alone|Pouze číslo týdne|Another patient's timetable alone|Pouze harmonogram jiného pacienta
neurology|a|How do localization and diagnosis differ?|Jak se liší lokalizace a diagnóza?|Localization identifies the affected region; diagnosis identifies the disease|Lokalizace určuje postiženou oblast; diagnóza určuje nemoc|Both terms mean the same disease name|Oba pojmy znamenají stejný název nemoci|Localization identifies only the patient's age|Lokalizace určuje pouze věk pacienta
neurology|b|Which finding can support a lower motor neuron pattern?|Který nález může podporovat obraz dolního motoneuronu?|Reduced muscle tone and reflexes|Snížený svalový tonus a reflexy|Increased coat density|Zvýšená hustota srsti|An isolated change in appetite|Izolovaná změna chuti k jídlu
neurology|c|What takes priority when severe new spinal pain or neurological deterioration appears?|Co má přednost při nové silné bolesti páteře nebo neurologickém zhoršení?|Prompt veterinary reassessment|Rychlé veterinární přehodnocení|Completion of the planned repetition count|Dokončení plánovaného počtu opakování|Recording the change only at the next routine visit|Záznam změny až při další běžné návštěvě
neurology|d|What does reflex stepping establish by itself?|Co samotné reflexní krokování dokládá?|A stepping response, not necessarily voluntary walking|Krokovou odpověď, nikoli nutně volní chůzi|Restored continence|Obnovenou kontinenci|Complete neurological recovery|Úplné neurologické zotavení
passive|a|What distinguishes passive movement from active strengthening?|Čím se pasivní pohyb liší od aktivního posilování?|An external force moves the joint|Kloubem pohybuje zevní síla|It always creates greater muscle force|Vždy vytváří větší svalovou sílu|It eliminates the need for active exercise|Odstraňuje potřebu aktivního cvičení
passive|b|Which statement distinguishes PROM from stretching?|Které tvrzení odlišuje PROM od protahování?|PROM explores joint range; stretching targets tissue length|PROM zkoumá rozsah kloubu; protahování cílí na délku tkáně|Both are names for electrical stimulation|Obojí je označení elektrostimulace|PROM measures body fat|PROM měří tělesný tuk
passive|c|Which condition may make joint mobilization inappropriate?|Který stav může činit kloubní mobilizaci nevhodnou?|Joint instability or a protected repair|Kloubní nestabilita nebo chráněná reparace|A quiet examination room|Klidná vyšetřovna|A recorded baseline measurement|Zaznamenané výchozí měření
passive|d|What should be monitored during massage?|Co je třeba sledovat během masáže?|Behavior and tissue response|Chování a reakci tkáně|Only the elapsed time|Pouze uplynulý čas|Only the therapist's hand speed|Pouze rychlost rukou terapeuta
active|a|What makes an exercise goal useful?|Co činí cíl cvičení užitečným?|A defined capacity or functional task with success criteria|Určená schopnost nebo funkční úkol s kritérii úspěchu|Choosing the most difficult exercise available|Volba nejtěžšího dostupného cviku|Avoiding baseline assessment|Vynechání výchozího hodnocení
active|b|What is the purpose of assistance during a task?|Jaký je účel dopomoci během úkolu?|Enable participation while preventing collapse or falls|Umožnit zapojení a zabránit podklesnutí či pádu|Remove all patient participation|Odstranit veškeré zapojení pacienta|Make every surface unstable|Učinit každý povrch nestabilním
active|c|How should reflex-induced movement be interpreted?|Jak se má interpretovat reflexně vyvolaný pohyb?|Separately from voluntary motor recovery|Odděleně od obnovy volní motoriky|As proof that voluntary control is normal|Jako důkaz normální volní kontroly|As proof that sensation is normal|Jako důkaz normálního čití
active|d|What should prompt stopping an exercise?|Co má být důvodem k přerušení cviku?|Pain, distress or loss of safe control|Bolest, stres nebo ztráta bezpečné kontroly|Completion of fewer repetitions than another patient|Méně opakování než u jiného pacienta|A planned recovery interval|Plánovaný interval zotavení
modalities|a|Why is impaired sensation relevant to heat or cold treatment?|Proč je porucha čití důležitá při aplikaci tepla nebo chladu?|It can hide developing thermal injury|Může skrýt vznikající tepelné poškození|It guarantees improved tolerance|Zaručuje lepší toleranci|It makes skin checks unnecessary|Činí kontrolu kůže zbytečnou
modalities|b|Which distinction matters in magnetic therapy?|Které rozlišení je důležité u magnetoterapie?|Pulsed electromagnetic fields differ from static magnets|Pulzní elektromagnetické pole se liší od statických magnetů|All magnetic devices have identical protocols|Všechny magnetické přístroje mají stejné protokoly|A proposed mechanism proves clinical benefit|Navržený mechanismus dokazuje klinický přínos
modalities|c|What affects exposure during therapeutic ultrasound?|Co ovlivňuje expozici při terapeutickém ultrazvuku?|Frequency, intensity, duty cycle and coupling|Frekvence, intenzita, pracovní cyklus a kontakt|Only the device's brand name|Pouze značka přístroje|Only the room lighting|Pouze osvětlení místnosti
modalities|d|Which pairing is correct?|Které přiřazení je správné?|TENS: sensory analgesia; NMES: evoked muscle contraction|TENS: senzitivní analgezie; NMES: vyvolaná svalová kontrakce|TENS: bone imaging; NMES: wound closure|TENS: zobrazení kostí; NMES: uzavření rány|TENS and NMES: identical goals and targets|TENS a NMES: stejné cíle a cílové struktury
modalities|e|What does a laser's class primarily describe?|Co především vyjadřuje třída laseru?|Its hazard classification|Klasifikaci nebezpečnosti|Proven effectiveness for every disease|Prokázanou účinnost u každé nemoci|A universal treatment duration|Univerzální délku ošetření
modalities|f|Does reduced pain after shockwave establish readiness for unrestricted load?|Potvrzuje menší bolest po rázové vlně připravenost k neomezené zátěži?|No; tissue load tolerance still needs assessment|Ne; toleranci zátěže tkáně je stále třeba posoudit|Yes; analgesia proves complete repair|Ano; analgezie dokazuje úplnou reparaci|Yes; tissue status is irrelevant afterward|Ano; stav tkáně poté není podstatný
hydrotherapy|a|Which water property reduces effective weight bearing?|Která vlastnost vody snižuje efektivní zatížení?|Buoyancy|Vztlak|Viscous resistance|Viskózní odpor|Belt speed|Rychlost pásu
hydrotherapy|b|Which observation calls for stopping water work?|Které pozorování je důvodem k přerušení práce ve vodě?|Panic, coughing or breathing difficulty|Panika, kašel nebo dechové obtíže|Calm, controlled participation|Klidné a kontrolované zapojení|Continuous supervision|Nepřetržitý dohled
support|a|Does urine leakage prove adequate bladder emptying?|Dokazuje únik moči dostatečné vyprázdnění měchýře?|No; leakage can coexist with retention|Ne; únik může být současně s retencí|Yes; leakage always means complete emptying|Ano; únik vždy znamená úplné vyprázdnění|Yes; bladder assessment is then unnecessary|Ano; hodnocení měchýře pak není potřebné
support|b|What matters most when selecting a mobility aid?|Co je nejdůležitější při volbě pohybové pomůcky?|Fit, appropriate support and patient participation|Usazení, vhodná opora a zapojení pacienta|Color matching with the leash|Barevná shoda s vodítkem|Choosing the largest device|Volba největší pomůcky
support|c|Which statement correctly distinguishes orthosis and prosthesis?|Které tvrzení správně odlišuje ortézu a protézu?|An orthosis supports; a prosthesis replaces a missing part|Ortéza podporuje; protéza nahrazuje chybějící část|An orthosis replaces; a prosthesis measures joint range|Ortéza nahrazuje; protéza měří rozsah kloubu|Both are names for massage techniques|Obojí je označení masážních technik
support|d|Can excess body fat coexist with muscle loss?|Může nadbytek tělesného tuku existovat současně s úbytkem svalů?|Yes; body and muscle condition are separate assessments|Ano; tělesná a svalová kondice se hodnotí odděleně|No; more fat always means more muscle|Ne; více tuku vždy znamená více svalů|No; body weight fully describes muscle condition|Ne; hmotnost plně popisuje svalovou kondici
support|e|Which goal fits palliative rehabilitation?|Který cíl odpovídá paliativní rehabilitaci?|Comfort and meaningful, tolerable daily activity|Komfort a smysluplná, snesitelná denní aktivita|Restoring athletic performance in every patient|Obnovení sportovního výkonu u každého pacienta|Increasing difficulty regardless of burden|Zvyšování obtížnosti bez ohledu na zátěž péče
cases|a|How should a useful problem list be organized?|Jak má být uspořádán užitečný seznam problémů?|Prioritized, separating findings from hypotheses|Podle priorit, s oddělením nálezů od hypotéz|Only by the order in which findings were noticed|Pouze podle pořadí, v jakém byly nálezy zaznamenány|With every hypothesis recorded as a confirmed diagnosis|Se všemi hypotézami zapsanými jako potvrzené diagnózy
cases|b|What should happen if important restrictions are missing from a medical report?|Co dělat, když ve zprávě chybí důležitá omezení?|Clarify them with the treating team|Vyjasnit je s léčebným týmem|Infer unrestricted activity from “doing well”|Odvodit neomezenou aktivitu z „daří se dobře“|Copy restrictions from an unrelated patient|Převzít omezení nesouvisejícího pacienta
cases|c|What connects an intervention to a reviewable plan?|Co propojuje intervenci s kontrolovatelným plánem?|A problem, goal, baseline and recorded response|Problém, cíl, výchozí stav a zaznamenaná reakce|Only the name of the technique|Pouze název techniky|Only a future appointment date|Pouze datum příští návštěvy
cases|d|How can you check that an owner understood home instructions?|Jak ověříte, že majitel porozuměl domácím pokynům?|Ask for an explanation and appropriate demonstration in their own words|Požádat o vysvětlení vlastními slovy a vhodnou ukázku|Assume that receiving a handout is enough|Předpokládat, že převzetí letáku stačí|Avoid asking about practical barriers|Neptat se na praktické překážky
special|a|Which approach fits a patient with obesity and osteoarthritis?|Který přístup odpovídá pacientovi s obezitou a osteoartrózou?|Combined pain care, nutrition, appropriate activity and home adaptations|Spojení péče o bolest, výživy, vhodné aktivity a úprav domova|Weight alone determines the exercise plan|Plán cvičení určuje samotná hmotnost|Joint pain and body condition are unrelated|Kloubní bolest a tělesná kondice spolu nesouvisejí
special|b|How should reduced jumping in an older cat be interpreted?|Jak posoudit omezené skákání starší kočky?|As a change that warrants assessment|Jako změnu vyžadující posouzení|As proof of normal aging without further assessment|Jako důkaz normálního stárnutí bez dalšího posouzení|As proof that joints are painless|Jako důkaz nebolestivých kloubů
special|c|What takes priority for a critically ill patient?|Co má přednost u kriticky nemocného pacienta?|Medical stabilization and the critical-care plan|Zdravotní stabilizace a plán intenzivní péče|Completion of a routine exercise program|Dokončení běžného cvičebního programu|Comparison with healthy athletic performance|Porovnání s výkonem zdravého sportovce
special|d|What determines exercise limits in cardiac disease?|Co určuje hranice zátěže při srdečním onemocnění?|Cardiac status and individual veterinary assessment|Srdeční stav a individuální veterinární posouzení|Age alone|Pouze věk|Whether the animal enjoys water|Zda má zvíře rádo vodu
`.trim().split('\n');
export const questions:Question[]=rows.map(row=>{
 const [topic,criterion,en,cs,...options]=row.split('|'),id=`${topic}-${criterion}-v1`,module=examModules.find(m=>m.id===topic),section=module?.sections.find(s=>s.criteria===criterion);
 if(!section||options.length!==6)throw Error(`Invalid quiz question: ${id}`);
 return {id,topic,criterion,prompt:{en,cs},choices:[0,1,2].map(n=>({id:`${id}-${n}`,text:{en:options[n*2],cs:options[n*2+1]}})),correctId:`${id}-0`,explanation:section.text};
});
for(const kind of ['skeleton','stifle'] as const){
 const p=photoData[kind];p.marks.forEach((mark,index)=>{
  const id=`photo-${kind}-${index+1}-v1`,names=[mark,...p.marks.filter(m=>m!==mark).slice(0,3)];
  questions.push({id,topic:kind==='skeleton'?'anatomy':'orthopedics',criterion:kind==='skeleton'?'b–d':'b',prompt:{en:`Which structure is marked ${index+1}?`,cs:`Která struktura je označena číslem ${index+1}?`},choices:names.map((m,n)=>({id:`${id}-${n}`,text:{en:m.name[0],cs:m.name[1]}})),correctId:`${id}-0`,explanation:{en:`${index+1}: ${mark.name[0]}. ${p.description[0]}`,cs:`${index+1}: ${mark.name[1]}. ${p.description[1]}`},photo:{kind,mark:index}});
 });
}
export const questionById=new Map(questions.map(q=>[q.id,q]));
