'use client';
import {sitePath} from './site-path';
import {useId,useState,type ReactNode} from 'react';
import {Eye,EyeOff,ArrowUpRight} from 'lucide-react';
import type {Language} from './i18n';
import {examSources} from './exam-data';
type Pair=[string,string];
type Mark={point:[number,number];label:[number,number];name:Pair};
export const photoData={
 skeleton:{file:'dog-skeleton-museum.jpg',width:3710,height:2783,title:['Canine skeleton · real specimen','Kostra psa · skutečný preparát'] as Pair,description:['German Shepherd skeleton from the Museum of Veterinary Anatomy, University of São Paulo. Identify the numbered bones; mounting and specimen preparation are visible.','Kostra německého ovčáka z Muzea veterinární anatomie Univerzity v São Paulu. Určete očíslované kosti; na snímku jsou patrné prvky montáže a preparace.'] as Pair,source:'https://commons.wikimedia.org/wiki/File:German_Shepherd_dog._%E2%80%9CCanis_lupus_familiaris%E2%80%9D.jpg',editor:'Rodrigo Tetsuo Argenton',marks:[
  {point:[.220,.179],label:[.12,.12],name:['Skull','Lebka']},{point:[.414,.337],label:[.37,.23],name:['Scapula','Lopatka']},{point:[.391,.470],label:[.28,.45],name:['Humerus','Pažní kost']},{point:[.563,.378],label:[.59,.22],name:['Rib','Žebro']},{point:[.755,.451],label:[.87,.40],name:['Femur','Stehenní kost']},{point:[.731,.625],label:[.86,.66],name:['Tibia','Holenní kost']}
 ] as Mark[]},
 stifle:{file:'dog-knee-museum.jpg',width:3872,height:2592,title:['Canine stifle · real specimen','Koleno psa · skutečný preparát'] as Pair,description:['Dissected, freeze-dried canine stifle from the same veterinary museum. The exposed fibula helps orient this oblique lateral view. Cruciate ligaments and menisci are not clearly exposed and are not labeled.','Vypreparované a lyofilizované psí koleno ze stejného veterinárního muzea. Odkrytá fibula pomáhá s orientací v šikmém laterálním pohledu. Zkřížené vazy a menisky nejsou jasně odkryté, proto nejsou označeny.'] as Pair,source:'https://commons.wikimedia.org/wiki/File:Knee_joint_of_dog.jpg',editor:'',marks:[
  {point:[.356,.172],label:[.19,.18],name:['Femur','Stehenní kost']},{point:[.532,.633],label:[.69,.67],name:['Tibia','Holenní kost']},{point:[.495,.613],label:[.35,.66],name:['Fibula','Lýtková kost']},{point:[.523,.272],label:[.68,.23],name:['Patella','Čéška']},{point:[.554,.359],label:[.71,.41],name:['Patellar ligament','Čéškový vaz']}
 ] as Mark[]}
};
function PhotoStudy({kind,language}:{kind:keyof typeof photoData;language:Language}){
 const [labels,setLabels]=useState(true),p=photoData[kind],i=language==='cs'?1:0;
 const e=(en:string,cs:string)=>i?cs:en;
 return <figure className="study-photo">
  <div className="visual-heading"><div><span className="eyebrow mint">{e('LOOK · NAME · REMEMBER','POZORUJTE · POJMENUJTE · ZAPAMATUJTE')}</span><h2>{p.title[i]}</h2></div><button aria-pressed={!labels} onClick={()=>setLabels(v=>!v)}>{labels?<EyeOff size={16}/>:<Eye size={16}/>} {labels?e('Hide names','Skrýt názvy'):e('Reveal names','Odhalit názvy')}</button></div>
  <div className="specimen-image"><img src={sitePath('/study/'+p.file)} alt={p.description[i]} width={p.width} height={p.height} loading="lazy"/><svg viewBox={`0 0 1000 ${1000*p.height/p.width}`} aria-hidden="true">{p.marks.map((m,n)=>{const h=1000*p.height/p.width,x=m.label[0]*1000,y=m.label[1]*h;return <g key={n}><line x1={x} y1={y} x2={m.point[0]*1000} y2={m.point[1]*h} stroke="#8df4dc" strokeWidth={2}/><circle cx={m.point[0]*1000} cy={m.point[1]*h} r={3.5} fill="#8df4dc"/><circle cx={x} cy={y} r={18} fill="#102f2b" stroke="#8df4dc" strokeWidth={2}/><text x={x} y={y+6} textAnchor="middle" fill="#eafff8" fontSize={18} fontWeight={700}>{n+1}</text></g>;})}</svg></div>
  <ol className="photo-key" aria-label={e('Numbered image key','Číslovaný klíč k obrázku')}>{p.marks.map((m,n)=><li key={n}><b>{n+1}</b><span>{labels?m.name[i]:e('Name this structure','Pojmenujte strukturu')}</span></li>)}</ol>
  <figcaption><p>{p.description[i]}</p><p className="visual-credit">{e('Photo','Foto')}: Museum of Veterinary Anatomy FMVZ USP / Wagner Souza e Silva{p.editor?`; ${e('source edit','úprava zdroje')}: ${p.editor}`:''}. {e('Original photo unchanged; numbered teaching overlay added. Overlay composition:','Původní fotografie beze změn; přidána číslovaná studijní vrstva. Kompozice s popisky:')} <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>. <a href={p.source} target="_blank" rel="noreferrer">{e('Image source','Zdroj fotografie')}</a> · <a href={sitePath('/study/'+p.file)} target="_blank" rel="noreferrer">{e('Open full-resolution photo','Otevřít fotografii v plném rozlišení')}<ArrowUpRight size={13}/></a></p></figcaption>
 </figure>;
}
const diagramInfo:Record<string,{title:Pair;caption:Pair;prompt:Pair;source:keyof typeof examSources}>={
 physiology:{title:['Two routes: reflex and perception','Dvě cesty: reflex a vnímání'],caption:['Functional pathway diagram, not an anatomical section. A spinal response and conscious perception are different observations.','Schéma funkčních drah, nikoli anatomický řez. Míšní odpověď a vědomé vnímání jsou rozdílná pozorování.'],prompt:['Trace the reflex route. Which additional destination is needed for conscious perception?','Sledujte reflexní cestu. Jaký další cíl je nutný pro vědomé vnímání?'],source:'neuro'},
 healing:{title:['Healing overlaps','Fáze hojení se překrývají'],caption:['Conceptual sequence only. Bar lengths do not represent days, tissue strength or a timetable for loading.','Pouze pojmová posloupnost. Délky pruhů nevyjadřují dny, pevnost tkáně ani harmonogram zatěžování.'],prompt:['Name the four phases and one main task of each.','Pojmenujte čtyři fáze a jeden hlavní úkol každé z nich.'],source:'healing'},
 assessment:{title:['One limb, one stride','Jedna končetina, jeden cyklus'],caption:['A stride runs from one initial contact to the next contact of the same limb. Stance and swing durations vary with gait and speed.','Cyklus kroku probíhá od prvního kontaktu do dalšího kontaktu stejné končetiny. Doba opory a švihu závisí na chodu a rychlosti.'],prompt:['Which part is spent in contact with the ground? When is the limb advancing off the ground?','Ve které části je končetina v kontaktu s podložkou? Kdy se přenáší bez kontaktu?'],source:'neuro'},
 passive:{title:['Measure the same angle','Měřte stále stejný úhel'],caption:['Goniometer principle, not a canine joint drawing or a normal-range target. Use the course protocol for anatomical landmarks and angle conventions.','Princip goniometru, nikoli kresba psího kloubu nebo cílový normální rozsah. Anatomické body a konvenci úhlu určuje protokol výuky.'],prompt:['Identify the axis and two reference lines. Why must positioning be repeatable?','Určete osu a dvě referenční přímky. Proč musí být poloha opakovatelná?'],source:'manual'},
 active:{title:['Three ways a muscle produces force','Tři způsoby tvorby svalové síly'],caption:['Idealized length changes while active tension is produced; blocks represent a muscle unit, not anatomical shape.','Idealizované změny délky při tvorbě aktivního napětí; bloky představují svalovou jednotku, nikoli anatomický tvar.'],prompt:['Name shortening, lengthening under tension and unchanged-length work.','Pojmenujte zkracování, prodlužování pod napětím a práci beze změny délky.'],source:'exercise'},
 modalities:{title:['Match the energy to the method','Přiřaďte energii k metodě'],caption:['A classification aid, not a ranking of effectiveness or a dosing guide. Shockwave and therapeutic ultrasound are distinct acoustic treatments.','Pomůcka ke třídění, nikoli pořadí účinnosti nebo návod k dávkování. Rázová vlna a terapeutický ultrazvuk jsou odlišné akustické metody.'],prompt:['Recall one method for each energy type. Explain TENS versus NMES.','Vybavte si jednu metodu pro každý druh energie. Vysvětlete rozdíl TENS a NMES.'],source:'exercise'},
 hydrotherapy:{title:['Water: support and resistance','Voda: podpora a odpor'],caption:['Forces on an abstract immersed object. Arrow sizes are illustrative, not measured. Buoyancy and resistance are different effects.','Síly na abstraktní ponořený objekt. Velikosti šipek jsou ilustrační, nikoli naměřené. Vztlak a odpor jsou odlišné účinky.'],prompt:['Which force opposes gravity? Which force opposes movement through water?','Která síla působí proti tíži? Která síla působí proti pohybu vodou?'],source:'rehab'},
 support:{title:['Two different roles for an aid','Dvě odlišné role pomůcky'],caption:['Concept comparison: an orthosis supports an existing segment; a prosthesis replaces a missing part. Suitability and fit require individual assessment.','Pojmové srovnání: ortéza podporuje existující segment, protéza nahrazuje chybějící část. Vhodnost a usazení vyžadují individuální posouzení.'],prompt:['Which device supports, and which replaces? What must be checked on the skin?','Která pomůcka podporuje a která nahrazuje? Co je nutné kontrolovat na kůži?'],source:'rehab'},
 cases:{title:['The rehabilitation reasoning loop','Cyklus rehabilitačního uvažování'],caption:['A memory map for presenting a case. The return arrow means reassess the response and revise the plan.','Paměťová mapa pro prezentaci případu. Zpětná šipka znamená znovu vyhodnotit reakci a upravit plán.'],prompt:['Start with findings. Connect the problem, goal, intervention and reassessment.','Začněte nálezy. Propojte problém, cíl, intervenci a přehodnocení.'],source:'pain'},
 special:{title:['Body fat ≠ muscle condition','Tělesný tuk ≠ svalová kondice'],caption:['Conceptual axes, not a validated scoring chart. Excess body fat can coexist with muscle loss; assess body and muscle condition separately.','Pojmové osy, nikoli validovaná hodnoticí škála. Nadbytečný tuk může existovat spolu s úbytkem svalů; tělesnou a svalovou kondici hodnoťte odděleně.'],prompt:['Find the quadrant that combines more body fat with less muscle.','Najděte oblast, která kombinuje více tělesného tuku s menším množstvím svalů.'],source:'senior'}
};
function MemoryDiagram({kind,language}:{kind:string;language:Language}){
 const id=useId().replaceAll(':',''),[labels,setLabels]=useState(true),i=language==='cs'?1:0,info=diagramInfo[kind];
 const e=(en:string,cs:string)=>i?cs:en;
 const text=(x:number,y:number,en:string,cs:string,extra={})=><text className="memory-label" x={x} y={y} textAnchor="middle" fill="#d8e9ef" fontSize={18} {...extra}>{e(en,cs).split('|').map((line,n)=><tspan key={n} x={x} dy={n?24:0}>{line}</tspan>)}</text>;
 const arrow=(x1:number,y1:number,x2:number,y2:number,color='#69dfc6')=><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth={3} markerEnd={`url(#${id}-${color==='#edb76b'?'gold':'mint'})`}/>;
 const box=(x:number,y:number,w:number,h:number,n:string,en:string,cs:string)=><g><rect x={x} y={y} width={w} height={h} rx={12} fill="#18342f" stroke="#47786d"/><circle cx={x+18} cy={y+18} r={11} fill="#6bdfcb"/><text x={x+18} y={y+23} textAnchor="middle" fontSize={13} fill="#09251e" fontWeight={700}>{n}</text>{text(x+w/2,y+h/2+8,en,cs)}</g>;
 let drawing:ReactNode;
 switch(kind){
 case 'physiology':drawing=<>{box(35,165,175,85,'1','Sensory input','Senzitivní vstup')}{box(275,165,170,85,'2','Spinal cord','Mícha')}{box(510,165,175,85,'3','Motor output','Motorický výstup')}{arrow(212,208,270,208)}{arrow(447,208,505,208)}{box(275,25,170,75,'4','Brain','Mozek')}{arrow(335,160,335,108,'#edb76b')}{arrow(385,107,385,160)}{text(148,292,'Receptor → CNS','Receptor → CNS')}{text(574,292,'Nerve → muscle','Nerv → sval')}{text(140,69,'Ascending|sensory pathways','Vzestupné|senzitivní dráhy')}{text(574,69,'Descending|motor control','Sestupné|motorické řízení')}</>;break;
 case 'healing':drawing=<>{[['Hemostasis','Hemostáza','Seal','Uzavření'],['Inflammation','Zánět','Clear','Odstranění'],['Proliferation','Proliferace','Build','Tvorba'],['Remodeling','Remodelace','Reorganize','Přestavba']].map((r,n)=><g key={n}><rect x={42+n*110} y={35+n*66} width={285} height={48} rx={24} fill={['#73522f','#6c3943','#235c53','#294f73'][n]} stroke={['#edb76b','#e18b99','#6bdfcb','#94c9f3'][n]}/><text x={65+n*110} y={66+n*66} fill="#fff" fontSize={18}>{n+1}</text>{text(190+n*110,66+n*66,r[0],r[1])}</g>)}{arrow(50,325,670,325)}{text(365,310,'Overlapping processes →','Překrývající se procesy →')}</>;break;
 case 'assessment':drawing=<><rect x={55} y={120} width={365} height={65} rx={10} fill="#23564b"/><rect x={425} y={120} width={240} height={65} rx={10} fill="#294e6d"/>{text(235,160,'Stance: ground contact','Opora: kontakt s podložkou')}{text(545,160,'Swing: no contact','Švih: bez kontaktu')}{[55,420,665].map((x,n)=><g key={x}><line x1={x} y1={93} x2={x} y2={214} stroke="#99b4c3" strokeWidth={2}/><circle cx={x} cy={80} r={17} fill="#193932" stroke="#6bdfcb"/><text x={x} y={86} textAnchor="middle" fill="#fff" fontSize={17}>{n+1}</text></g>)}{text(97,54,'Initial contact','První kontakt')}{text(420,54,'Toe-off','Odlepení tlapky')}{text(620,54,'Next contact','Další kontakt')}{arrow(58,247,660,247)}{text(360,290,'One stride of the same limb','Jeden cyklus stejné končetiny')}</>;break;
 case 'passive':drawing=<><line x1={340} y1={250} x2={110} y2={250} stroke="#b8c5cf" strokeWidth={15} strokeLinecap="round"/><line x1={340} y1={250} x2={485} y2={67} stroke="#b8c5cf" strokeWidth={15} strokeLinecap="round"/><path d="M250 250 A90 90 0 0 1 396 180" fill="none" stroke="#edb76b" strokeWidth={4}/><circle cx={340} cy={250} r={12} fill="#6bdfcb"/>{text(148,205,'Proximal reference','Proximální reference')}{text(570,114,'Distal reference','Distální reference')}{text(324,164,'Joint angle','Kloubní úhel')}{text(435,300,'Axis / pivot','Osa / střed otáčení')}{arrow(413,281,354,257)}</>;break;
 case 'active':drawing=<>{[['Concentric','Koncentrická','Shortens','Zkracuje se'],['Eccentric','Excentrická','Lengthens','Prodlužuje se'],['Isometric','Izometrická','Length unchanged','Délka se nemění']].map((r,n)=>{const x=35+n*235;return <g key={n}><rect x={x} y={36} width={210} height={277} rx={12} fill="#152831" stroke="#385462"/>{text(x+105,77,r[0],r[1])}<rect x={x+48} y={113} width={114} height={36} rx={10} fill="none" stroke="#90a9b6" strokeDasharray="5 5"/><rect x={x+(n===0?70:n===1?26:48)} y={204} width={n===0?70:n===1?158:114} height={36} rx={10} fill="#b96573" stroke="#e69aa5"/>{arrow(x+105,159,x+105,190)}{text(x+105,280,r[2],r[3])}</g>;})}</>;break;
 case 'modalities':drawing=<>{[['Thermal','Tepelná','Heat / cold','Teplo / chlad'],['Electrical','Elektrická','TENS / NMES','TENS / NMES'],['Light','Světelná','Laser / PBM','Laser / PBM'],['Magnetic','Magnetická','Pulsed fields','Pulzní pole'],['Acoustic','Akustická','Ultrasound','Ultrazvuk'],['Pressure waves','Tlakové vlny','Shockwave','Rázová vlna']].map((r,n)=>{const x=35+(n%3)*235,y=25+Math.floor(n/3)*155;return <g key={n}><rect x={x} y={y} width={210} height={130} rx={12} fill="#182e39" stroke="#456675"/><path d={`M${x+65} ${y+28} q10 -18 20 0 t20 0 t20 0 t20 0`} fill="none" stroke={n%2?'#edb76b':'#6bdfcb'} strokeWidth={3}/>{text(x+105,y+68,r[0],r[1])}{text(x+105,y+103,r[2],r[3],{fontSize:16,fill:'#9cc3cd'})}</g>;})}</>;break;
 case 'hydrotherapy':drawing=<><path d="M160 65 V305 H560 V65" fill="#163c50" stroke="#81b3cd" strokeWidth={3}/><path d="M162 91 q20 -10 40 0 t40 0 t40 0 t40 0 t40 0 t40 0 t40 0 t40 0 t40 0 t38 0" fill="none" stroke="#85cbea" strokeWidth={3}/><rect x={310} y={154} width={100} height={75} rx={10} fill="#bdc8cb"/>{arrow(360,150,360,108)}{arrow(360,235,360,285,'#edb76b')}{arrow(415,180,507,180,'#edb76b')}{arrow(305,207,208,207)}{text(360,51,'Buoyancy ↑','Vztlak ↑')}{text(360,333,'Gravity ↓','Tíže ↓')}{text(566,152,'Movement →','Pohyb →')}{text(132,249,'← Resistance','← Odpor')}</>;break;
 case 'support':drawing=<>{box(50,25,275,80,'1','Orthosis','Ortéza')}{box(395,25,275,80,'2','Prosthesis','Protéza')}<rect x={163} y={138} width={50} height={134} rx={14} fill="#b8c8cf"/><path d="M146 145 V273 M230 145 V273 M144 169 H232 M144 244 H232" fill="none" stroke="#6bdfcb" strokeWidth={8}/><rect x={506} y={138} width={50} height={58} rx={12} fill="#b8c8cf"/><path d="M503 182 H559 V271 H503 Z" fill="#326455" stroke="#6bdfcb" strokeWidth={3}/>{text(185,315,'Supports what is present','Podporuje přítomnou část')}{text(533,315,'Replaces what is missing','Nahrazuje chybějící část')}</>;break;
 case 'cases':drawing=<>{box(30,40,185,85,'1','Findings','Nálezy')}{box(270,40,185,85,'2','Functional goal','Funkční cíl')}{box(510,40,185,85,'3','Intervention','Intervence')}{arrow(218,83,262,83)}{arrow(458,83,502,83)}{box(270,215,185,85,'4','Reassessment','Přehodnocení')}<path d={`M603 130 V256 H463`} stroke="#6bdfcb" strokeWidth={3} fill="none" markerEnd={`url(#${id}-mint)`}/><path d={`M265 257 H122 V132`} stroke="#6bdfcb" strokeWidth={3} fill="none" markerEnd={`url(#${id}-mint)`}/>{text(560,320,'Observe response','Sledujte reakci')}{text(143,320,'Revise the plan','Upravte plán')}</>;break;
 default:drawing=<><rect x={353} y={175} width={260} height={100} fill="#5b422b" opacity={.7}/>{arrow(95,275,645,275)}{arrow(95,275,95,30)}<line x1={355} y1={35} x2={355} y2={272} stroke="#5c7380" strokeDasharray="5 5"/><line x1={98} y1={175} x2={630} y2={175} stroke="#5c7380" strokeDasharray="5 5"/>{text(365,319,'Body fat: less → more','Tělesný tuk: méně → více')}{text(187,53,'More muscle','Více svalů')}{text(193,250,'Less muscle','Méně svalů')}{text(482,214,'Excess fat +','Nadbytek tuku +')}{text(482,243,'muscle loss','úbytek svalů')}<circle cx={564} cy={229} r={8} fill="#edb76b"/></>;
 }
 const source=examSources[info.source];
 return <figure className={`memory-figure ${labels?'':'labels-off'}`}>
  <div className="visual-heading"><div><span className="eyebrow mint">{e('VISUAL MEMORY AID','OBRAZOVÁ POMŮCKA')}</span><h2>{info.title[i]}</h2></div><button aria-pressed={!labels} onClick={()=>setLabels(v=>!v)}>{labels?<EyeOff size={16}/>:<Eye size={16}/>} {labels?e('Hide labels','Skrýt popisky'):e('Reveal labels','Odhalit popisky')}</button></div>
  <div className="memory-scroll" tabIndex={0} aria-label={e('Study diagram; scroll horizontally on a small screen','Studijní schéma; na malé obrazovce posouvejte vodorovně')}><svg viewBox="0 0 740 355" role="img" aria-labelledby={`${id}-title ${id}-desc`}><title id={`${id}-title`}>{info.title[i]}</title><desc id={`${id}-desc`}>{labels?info.caption[i]:info.prompt[i]}</desc><defs>{[['mint','#69dfc6'],['gold','#edb76b']].map(([name,color])=><marker key={name} id={`${id}-${name}`} markerWidth={8} markerHeight={8} refX={7} refY={4} orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill={color}/></marker>)}</defs>{drawing}</svg></div>
  <figcaption><p className="visual-prompt">{info.prompt[i]}</p><p>{info.caption[i]}</p><p className="visual-credit">{e('Original teaching diagram · supporting reference','Vlastní studijní schéma · odborný podklad')}: <a href={source.url} target="_blank" rel="noreferrer">{source.title[language]}</a></p></figcaption>
 </figure>;
}
export default function StudyVisuals({topic,language}:{topic:string;language:Language}){
 if(topic==='anatomy')return <PhotoStudy kind="skeleton" language={language}/>;
 if(topic==='orthopedics')return <PhotoStudy kind="stifle" language={language}/>;
 const kind=topic==='neurology'?'physiology':topic;
 if(!diagramInfo[kind])return null;
 return <MemoryDiagram kind={kind} language={language}/>;
}
